import type {Category,Product,Restaurant} from "./types";

export const demoRestaurant:Restaurant={
  id:"demo",name:"Bistro Nube",slug:"bistro-nube",
  description:"Una carta que flota entre sabores.",translations:{en:{description:"A menu floating among flavors."}},
  logo_url:null,cover_url:null,primary_color:"#7c3aed",secondary_color:"#ec4899",currency:"EUR",locale:"es-ES",is_published:true,language_switcher_enabled:true,
  phone:"+34 600 123 456",address:"Calle del Cielo, 12 · Madrid",email:"hola@bistronube.es",instagram_url:null,website_url:null,
};

const categoryData=[
  {id:"1",name:"Hamburguesas",nameEn:"Burgers",slug:"hamburguesas"},
  {id:"4",name:"Carnes y brasas",nameEn:"Meat and grill",slug:"carnes-brasas"},
  {id:"5",name:"Pastas",nameEn:"Pasta",slug:"pastas"},
  {id:"0",name:"Entrantes",nameEn:"Starters",slug:"entrantes"},
  {id:"2",name:"Postres",nameEn:"Desserts",slug:"postres"},
  {id:"6",name:"Cócteles",nameEn:"Cocktails",slug:"cocteles"},
] as const;

export const demoCategories:Category[]=categoryData.map(({id,name,nameEn,slug},sort_order)=>({id,name,translations:{en:{name:nameEn}},slug,sort_order,is_active:true}));

type DemoProduct=Omit<Product,"categories"|"category_id"|"is_available"|"is_featured">&{categoryId:string;featured?:boolean};

function createDemoProduct(input:DemoProduct):Product{
  const category=demoCategories.find(item=>item.id===input.categoryId);
  if(!category)throw new Error(`Categoría demo desconocida: ${input.categoryId}`);
  const {categoryId,featured=false,...product}=input;
  return {...product,category_id:categoryId,is_available:true,is_featured:featured,categories:{name:category.name,translations:category.translations}};
}

export const demoProducts:Product[]=[
  createDemoProduct({id:"1",categoryId:"1",name:"Hamburguesa Nebulosa",description:"Carne madurada, cheddar, cebolla caramelizada y salsa secreta en pan brioche.",translations:{en:{name:"Nebula Burger",description:"Aged beef, cheddar, caramelized onion and secret sauce on brioche."}},price_cents:1290,video_url:"https://videos.pexels.com/video-files/19107070/19107070-hd_1080_1920_30fps.mp4",image_url:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=82",allergens:["gluten","eggs","milk"],sort_order:0,featured:true}),
  createDemoProduct({id:"2",categoryId:"1",name:"Smash Trufada",description:"Doble smash, cheddar, cebolla crujiente y mayonesa de trufa.",translations:{en:{name:"Truffle Smash",description:"Double smash patty, cheddar, crispy onion and truffle mayonnaise."}},price_cents:1490,video_url:"https://videos.pexels.com/video-files/5907166/5907166-hd_1080_1920_25fps.mp4",image_url:"https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=82",allergens:["gluten","eggs","milk"],sort_order:1}),
  createDemoProduct({id:"3",categoryId:"1",name:"Brisket Fuego",description:"Brisket cocinado lentamente, queso ahumado, pepinillos y salsa BBQ.",translations:{en:{name:"Fire Brisket",description:"Slow-cooked brisket, smoked cheese, pickles and BBQ sauce."}},price_cents:1590,video_url:"https://videos.pexels.com/video-files/5907167/5907167-hd_720_1280_50fps.mp4",image_url:"https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1200&q=82",allergens:["gluten","milk"],sort_order:2}),
  createDemoProduct({id:"4",categoryId:"4",name:"Entrecot de Encina",description:"Carne madurada al punto de brasa, jugo reducido y sal ahumada.",translations:{en:{name:"Oak-Grilled Entrecôte",description:"Aged beef grilled over oak, reduced jus and smoked salt."}},price_cents:2490,video_url:"https://videos.pexels.com/video-files/8477342/8477342-hd_720_1280_24fps.mp4",image_url:"https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1200&q=82",sort_order:3}),
  createDemoProduct({id:"5",categoryId:"4",name:"Costilla Glaseada",description:"Costilla a baja temperatura con glaseado especiado y hierbas frescas.",translations:{en:{name:"Glazed Ribs",description:"Slow-cooked ribs with spiced glaze and fresh herbs."}},price_cents:2190,video_url:"https://videos.pexels.com/video-files/4230556/4230556-hd_720_1280_60fps.mp4",image_url:"https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=82",sort_order:4}),
  createDemoProduct({id:"6",categoryId:"4",name:"Solomillo de Autor",description:"Solomillo marcado, crema de patata y salsa de vino tinto.",translations:{en:{name:"Signature Tenderloin",description:"Seared tenderloin, potato cream and red wine sauce."}},price_cents:2790,video_url:"https://videos.pexels.com/video-files/8477337/8477337-hd_720_1280_24fps.mp4",image_url:"https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1200&q=82",allergens:["milk"],sort_order:5}),
  createDemoProduct({id:"7",categoryId:"5",name:"Tagliatelle al Tartufo",description:"Pasta fresca, crema de parmesano, trufa negra y pimienta recién molida.",translations:{en:{name:"Truffle Tagliatelle",description:"Fresh pasta, parmesan cream, black truffle and cracked pepper."}},price_cents:1690,video_url:"https://videos.pexels.com/video-files/6247894/6247894-hd_1080_1920_24fps.mp4",image_url:"https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=82",allergens:["gluten","eggs","milk"],sort_order:6}),
  createDemoProduct({id:"8",categoryId:"5",name:"Rigatoni de la Casa",description:"Rigatoni al dente, tomate asado, albahaca fresca y queso curado.",translations:{en:{name:"House Rigatoni",description:"Al dente rigatoni, roasted tomato, fresh basil and aged cheese."}},price_cents:1450,video_url:"https://videos.pexels.com/video-files/6247888/6247888-hd_1080_1920_24fps.mp4",image_url:"https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?auto=format&fit=crop&w=1200&q=82",allergens:["gluten","milk"],sort_order:7}),
  createDemoProduct({id:"9",categoryId:"5",name:"Carbonara Cremosa",description:"Pasta larga, guanciale crujiente, pecorino y yema de huevo.",translations:{en:{name:"Creamy Carbonara",description:"Long pasta, crispy guanciale, pecorino and egg yolk."}},price_cents:1590,video_url:"https://videos.pexels.com/video-files/5708472/5708472-hd_720_1280_50fps.mp4",image_url:"https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=82",allergens:["gluten","eggs","milk"],sort_order:8}),
  createDemoProduct({id:"10",categoryId:"0",name:"Papas Voladoras",description:"Patata crujiente, parmesano, hierbas y mayonesa ahumada.",translations:{en:{name:"Flying Potatoes",description:"Crispy potatoes, parmesan, herbs and smoked mayonnaise."}},price_cents:690,video_url:"https://res.cloudinary.com/det6jfwzx/video/upload/v1783700440/id_papas_voladoras______nom_jqf6ng.mp4",image_url:"https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=1200&q=82",allergens:["eggs","milk"],sort_order:9}),
  createDemoProduct({id:"11",categoryId:"0",name:"Tapas del Mercado",description:"Selección de bocados crujientes con salsas de la casa.",translations:{en:{name:"Market Tapas",description:"A selection of crispy bites with house sauces."}},price_cents:1190,video_url:"https://videos.pexels.com/video-files/19107069/19107069-hd_1080_1920_30fps.mp4",image_url:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=82",allergens:["gluten","eggs"],sort_order:10}),
  createDemoProduct({id:"12",categoryId:"0",name:"Bruschetta Mediterránea",description:"Pan crujiente, tomate fresco, aceitunas, albahaca y aceite de oliva.",translations:{en:{name:"Mediterranean Bruschetta",description:"Crispy bread, fresh tomato, olives, basil and olive oil."}},price_cents:790,video_url:"https://videos.pexels.com/video-files/5617531/5617531-hd_1080_1920_25fps.mp4",image_url:"https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=1200&q=82",allergens:["gluten"],sort_order:11}),
  createDemoProduct({id:"13",categoryId:"2",name:"Tarta de Queso Stratos",description:"Tarta de queso al estilo San Sebastián con corazón cremoso.",translations:{en:{name:"Stratos Cheesecake",description:"San Sebastián-style cheesecake with a creamy center."}},price_cents:650,video_url:"https://videos.pexels.com/video-files/4547597/4547597-hd_1080_1920_25fps.mp4",image_url:"https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=1200&q=82",allergens:["gluten","eggs","milk"],sort_order:12}),
  createDemoProduct({id:"14",categoryId:"2",name:"Chocolate Eclipse",description:"Bizcocho intenso de cacao, ganache caliente y crema de vainilla.",translations:{en:{name:"Chocolate Eclipse",description:"Rich cocoa sponge, warm ganache and vanilla cream."}},price_cents:690,video_url:"https://videos.pexels.com/video-files/5945051/5945051-hd_1080_1920_25fps.mp4",image_url:"https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=82",allergens:["gluten","eggs","milk"],sort_order:13}),
  createDemoProduct({id:"15",categoryId:"2",name:"Frutos Rojos y Vainilla",description:"Crema ligera de vainilla, frutos rojos y crumble de almendra.",translations:{en:{name:"Berries and Vanilla",description:"Light vanilla cream, red berries and almond crumble."}},price_cents:620,video_url:"https://videos.pexels.com/video-files/5944917/5944917-hd_1080_1920_25fps.mp4",image_url:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=82",allergens:["nuts","milk"],sort_order:14}),
  createDemoProduct({id:"16",categoryId:"6",name:"Negroni Nube",description:"Ginebra, vermut rojo, bitter italiano y piel de naranja.",translations:{en:{name:"Cloud Negroni",description:"Gin, red vermouth, Italian bitter and orange peel."}},price_cents:950,video_url:"https://videos.pexels.com/video-files/7219291/7219291-hd_720_1280_24fps.mp4",image_url:"https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1200&q=82",sort_order:15}),
  createDemoProduct({id:"17",categoryId:"6",name:"Mojito Jardín",description:"Ron blanco, lima fresca, hierbabuena, soda y hielo picado.",translations:{en:{name:"Garden Mojito",description:"White rum, fresh lime, mint, soda and crushed ice."}},price_cents:890,video_url:"https://videos.pexels.com/video-files/8085092/8085092-hd_1080_1920_25fps.mp4",image_url:"https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=1200&q=82",sort_order:16}),
  createDemoProduct({id:"18",categoryId:"6",name:"Pasión Ahumada",description:"Maracuyá, cítricos, vainilla y un acabado aromático ahumado.",translations:{en:{name:"Smoked Passion",description:"Passion fruit, citrus, vanilla and an aromatic smoked finish."}},price_cents:990,video_url:"https://videos.pexels.com/video-files/4725772/4725772-hd_1080_1920_25fps.mp4",image_url:"https://images.unsplash.com/photo-1560512823-829485b8bf24?auto=format&fit=crop&w=1200&q=82",sort_order:17}),
];
