import type {Category,Product,Restaurant} from "./types";
export const demoRestaurant:Restaurant={id:"demo",name:"Bistro Nube",slug:"bistro-nube",description:"Una carta que flota entre sabores.",logo_url:null,cover_url:null,primary_color:"#7c3aed",secondary_color:"#ec4899",currency:"EUR",locale:"es-ES",is_published:true,phone:"+34 600 123 456",address:"Calle del Cielo, 12 · Madrid",email:"hola@bistronube.es",instagram_url:null,website_url:null};
export const demoCategories:Category[]=["Entrantes","Hamburguesas","Postres","Bebidas"].map((name,i)=>({id:String(i),name,slug:name.toLowerCase(),sort_order:i,is_active:true}));
export const demoProducts:Product[]=[
 {id:"1",category_id:"1",name:"Hamburguesa Nebulosa",description:"200g de carne madurada, queso cheddar derretido, cebolla caramelizada y nuestra salsa secreta en pan brioche de la casa.",price_cents:1290,video_url:"https://res.cloudinary.com/det6jfwzx/video/upload/v1783700256/Generame_un_video_de_una_hambu_oo9gur.mp4",image_url:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1400&q=85",is_available:true,is_featured:true,sort_order:0,categories:{name:"Hamburguesas"}},
 {id:"2",category_id:"0",name:"Papas Voladoras",description:"Papas rústicas cortadas a mano, doble cocción, especias ahumadas y alioli de ajo negro.",price_cents:650,video_url:"https://res.cloudinary.com/det6jfwzx/video/upload/v1783700440/id_papas_voladoras______nom_jqf6ng.mp4",image_url:"https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=1400&q=85",is_available:true,is_featured:false,sort_order:1,categories:{name:"Entrantes"}},
 {id:"3",category_id:"2",name:"Tarta de Queso Stratos",description:"Tarta de queso horneada al estilo San Sebastián, con un corazón ultra cremoso.",price_cents:550,video_url:"https://res.cloudinary.com/det6jfwzx/video/upload/v1783700598/id_tarta_queso_stratos__vnhgmf.mp4",image_url:"https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=1400&q=85",is_available:true,is_featured:false,sort_order:2,categories:{name:"Postres"}},
 {id:"4",category_id:"3",name:"Limonada Flotante",description:"Zumo de limón natural, menta fresca, jengibre y sirope de agave con hielo picado.",price_cents:390,video_url:null,image_url:"https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1400&q=85",is_available:true,is_featured:false,sort_order:3,categories:{name:"Bebidas"}}
];
