import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {LegalPage, LegalSection} from "@/components/legal/legal-page";
import {getLegalIdentity} from "@/lib/legal";

export const metadata:Metadata={title:"Encargo de tratamiento | Carta Video",robots:{index:false,follow:false}};

export default function DpaPage(){const identity=getLegalIdentity();if(!identity.complete)notFound();return <LegalPage title="Acuerdo de encargo de tratamiento" summary="Anexo aplicable cuando Carta Video trata datos personales siguiendo instrucciones de un restaurante cliente." identity={identity}>
  <LegalSection title="1. Partes y roles"><p>El restaurante cliente actúa como responsable del tratamiento y {identity.name}, proveedor de Carta Video, como encargado. Este acuerdo forma parte de las condiciones del servicio y se aplica durante la prestación.</p></LegalSection>
  <LegalSection title="2. Objeto y finalidad"><p>El encargo comprende el alojamiento, organización, soporte, seguridad, visualización y, cuando se active, traducción de los datos incorporados por el restaurante para operar su carta y panel. No se tratarán para finalidades propias incompatibles.</p></LegalSection>
  <LegalSection title="3. Personas y datos"><p>Puede afectar a personal y colaboradores del restaurante, contactos de soporte y otras personas cuyos datos incorpore el responsable. Los datos pueden incluir identificación, contacto, rol, comunicaciones, contenido de la carta y registros técnicos. No debe incorporarse información especialmente sensible salvo acuerdo previo y necesidad justificada.</p></LegalSection>
  <LegalSection title="4. Instrucciones y confidencialidad"><p>El encargado tratará los datos únicamente conforme a instrucciones documentadas del responsable y a la normativa. Si considera que una instrucción infringe la ley, lo comunicará. El personal autorizado estará sujeto a deber de confidencialidad.</p></LegalSection>
  <LegalSection title="5. Seguridad"><p>Se aplicarán medidas proporcionadas al riesgo, incluidas autenticación, control por roles, aislamiento lógico entre restaurantes, políticas de acceso a datos, gestión protegida de secretos, cifrado en tránsito, registros técnicos, copias de seguridad del proveedor y procedimientos de eliminación.</p></LegalSection>
  <LegalSection title="6. Subencargados"><p>Se autoriza con carácter general el uso de Supabase, Vercel, Cloudinary y DeepL para las funciones descritas, y Stripe solo cuando se active el pago integrado. El encargado impondrá obligaciones de protección equivalentes y comunicará cambios materiales con antelación razonable para que el responsable pueda formular una objeción fundada.</p></LegalSection>
  <LegalSection title="7. Transferencias"><p>Cuando un subencargado trate datos fuera del Espacio Económico Europeo, se aplicará un mecanismo válido conforme al RGPD, como una decisión de adecuación o cláusulas contractuales tipo, junto con medidas adicionales cuando proceda.</p></LegalSection>
  <LegalSection title="8. Asistencia"><p>El encargado ayudará razonablemente al responsable a responder derechos de las personas, evaluar riesgos, realizar consultas o evaluaciones de impacto y cumplir obligaciones de seguridad, teniendo en cuenta la naturaleza del tratamiento y la información disponible.</p></LegalSection>
  <LegalSection title="9. Violaciones de seguridad"><p>El encargado notificará al responsable sin dilación indebida las violaciones de seguridad de datos personales de las que tenga conocimiento y aportará la información disponible necesaria para su gestión y, cuando corresponda, notificación.</p></LegalSection>
  <LegalSection title="10. Finalización"><p>Al terminar el servicio, y a elección del responsable cuando sea técnicamente viable, se devolverán o eliminarán los datos tratados por su cuenta, salvo obligación legal de conservación. Las copias de seguridad se suprimirán conforme a sus ciclos técnicos y permanecerán protegidas mientras existan.</p></LegalSection>
  <LegalSection title="11. Evidencias y auditoría"><p>El encargado facilitará información razonable para demostrar el cumplimiento y permitirá auditorías proporcionadas, sujetas a confidencialidad, coordinación previa y evitando interferencias innecesarias o acceso a datos de otros clientes.</p></LegalSection>
  <LegalSection title="12. Obligaciones del responsable"><p>El restaurante garantiza una base jurídica válida, informa a las personas afectadas, limita los datos a lo necesario, mantiene instrucciones lícitas y configura correctamente usuarios y permisos. También debe comunicar con rapidez cualquier solicitud o incidente relevante.</p></LegalSection>
</LegalPage>}
