"use client";

import {useState} from "react";
import {CheckCircle2,ChefHat,Clock3} from "lucide-react";
import type {CartLine} from "@/lib/menu-cart";

export type TableOrderingContext={tableCode:string;tableName:string;active:boolean;expiresAt:string|null};

export function TableOrderCheckout({context,lines,language,accent,background,onSent}:{context:TableOrderingContext;lines:CartLine[];language:"es"|"en";accent:string;background:string;onSent:()=>void}){
  const[note,setNote]=useState("");const[sending,setSending]=useState(false);const[sent,setSent]=useState<string|null>(null);const[error,setError]=useState("");
  const es=language==="es";
  async function submit(){if(sending||!context.active)return;setSending(true);setError("");try{const response=await fetch("/api/public/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tableCode:context.tableCode,lines,customerNote:note})});const payload=await response.json() as {error?:string;order?:{number:string}};if(!response.ok||!payload.order)throw new Error(payload.error??"No se pudo enviar el pedido.");setSent(payload.order.number);setNote("");onSent()}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo enviar el pedido.")}finally{setSending(false)}}
  if(sent)return <div className="mt-4 border border-emerald-400/30 bg-emerald-500/10 p-4 text-center"><CheckCircle2 className="mx-auto text-emerald-400"/><p className="mt-2 font-bold">{es?"Pedido enviado a cocina":"Order sent to the kitchen"}</p><p className="mt-1 text-xs text-white/65">{es?`Pedido #${sent} · ${context.tableName}`:`Order #${sent} · ${context.tableName}`}</p><button type="button" onClick={()=>setSent(null)} className="mt-3 border border-white/20 px-3 py-2 text-xs font-bold">{es?"Hacer otro pedido":"Place another order"}</button></div>;
  return <div className="mt-4 border-t border-white/15 pt-4"><div className="flex items-center gap-2"><ChefHat size={17} style={{color:accent}}/><strong className="text-sm">{context.tableName}</strong>{context.expiresAt&&<span className="ml-auto flex items-center gap-1 text-[10px] text-white/55"><Clock3 size={12}/>{new Intl.DateTimeFormat(es?"es-ES":"en-GB",{hour:"2-digit",minute:"2-digit"}).format(new Date(context.expiresAt))}</span>}</div>{context.active?<><textarea value={note} onChange={event=>setNote(event.target.value.slice(0,300))} maxLength={300} placeholder={es?"Nota general para cocina (opcional)":"General kitchen note (optional)"} className="mt-3 min-h-16 w-full resize-none border border-white/15 bg-black/20 p-3 text-xs text-white outline-none placeholder:text-white/40"/><button type="button" disabled={sending} onClick={()=>void submit()} style={{background:accent,color:background}} className="mt-2 min-h-11 w-full px-4 py-3 text-sm font-black disabled:opacity-60">{sending?(es?"Enviando…":"Sending…"):(es?"Enviar pedido a cocina":"Send order to kitchen")}</button></>:<p className="mt-3 border border-amber-300/25 bg-amber-500/10 p-3 text-xs leading-relaxed text-amber-100">{es?"Esta mesa está cerrada. Pide al personal que la active para enviar el pedido.":"This table is closed. Ask staff to activate it before ordering."}</p>}{error&&<p role="alert" className="mt-2 text-xs font-semibold text-red-300">{error}</p>}</div>;
}
