"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowLeft,Info,Menu,Share2,Volume2,VolumeX,X} from "lucide-react";
import type {Product,Restaurant} from "@/lib/types";

export function VideoMenu({restaurant,products}:{restaurant:Restaurant;products:Product[]}){
 const refs=useRef<(HTMLVideoElement|null)[]>([]);const [muted,setMuted]=useState(true);const [open,setOpen]=useState(false);
 const categories=[...new Map(products.map(p=>[p.categories?.name??"Carta",p])).entries()];
 useEffect(()=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{const video=entry.target as HTMLVideoElement;if(entry.isIntersecting&&entry.intersectionRatio>.7){refs.current.forEach(other=>{if(other&&other!==video){other.pause();other.currentTime=0}});video.currentTime=0;void video.play().catch(()=>undefined)}else{video.pause();video.currentTime=0}}),{threshold:[.7]});refs.current.forEach(video=>video&&observer.observe(video));return()=>observer.disconnect()},[products]);
 const share=async()=>{try{await navigator.share({title:restaurant.name,url:location.href})}catch{await navigator.clipboard.writeText(location.href)}};
 const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});setOpen(false)};
 return <main className="snap bg-slate-950 md:mx-auto md:max-w-[430px] md:border-x md:border-white/15">
  {open&&<aside className="glass fixed inset-x-4 top-20 z-30 max-w-md rounded-2xl p-5 md:left-1/2 md:right-auto md:w-[398px] md:-translate-x-1/2"><div className="flex items-center justify-between"><b>Explorar carta</b><button aria-label="Cerrar menú" onClick={()=>setOpen(false)}><X/></button></div><div className="mt-4 flex flex-wrap gap-2">{categories.map(([name,p])=><button key={name} onClick={()=>go(`product-${p.id}`)} className="rounded-full bg-white/15 px-3 py-2 text-sm">{name}</button>)}</div><div className="mt-5 border-t border-white/20 pt-4 text-sm text-slate-200"><p>{restaurant.description}</p>{restaurant.address&&<p className="mt-2">{restaurant.address}</p>}{restaurant.phone&&<a className="mt-2 block underline" href={`tel:${restaurant.phone}`}>{restaurant.phone}</a>}{restaurant.instagram_url&&<a className="mt-2 block underline" target="_blank" href={restaurant.instagram_url}>Instagram</a>}{restaurant.website_url&&<a className="mt-2 block underline" target="_blank" href={restaurant.website_url}>Visitar web</a>}</div></aside>}
  <header className="glass fixed left-4 right-4 top-4 z-20 flex items-center justify-between rounded-2xl px-4 py-3 md:left-1/2 md:right-auto md:w-[398px] md:-translate-x-1/2"><button aria-label="Volver" onClick={()=>history.length>1?history.back():location.assign("/")} className="p-1"><ArrowLeft size={19}/></button><b>{restaurant.name}</b><div className="flex items-center gap-3"><button aria-label="Compartir carta" onClick={share}><Share2 size={19}/></button><button aria-label="Abrir menú" onClick={()=>setOpen(true)}><Menu size={20}/></button></div></header>
  {products.map((product,index)=><section id={`product-${product.id}`} key={product.id} className="relative isolate flex items-end overflow-hidden p-5 md:p-6"><div className="absolute inset-0 -z-10 bg-slate-800" style={{backgroundImage:product.image_url?`linear-gradient(0deg,rgba(2,6,23,.92),rgba(2,6,23,.1)),url(${product.image_url})`:undefined,backgroundSize:"cover",backgroundPosition:"center"}}>{product.video_url&&<video ref={element=>{refs.current[index]=element}} src={product.video_url} poster={product.image_url??undefined} muted={muted} loop playsInline preload="metadata" className="h-full w-full object-cover"/>}</div><div className="max-w-xl"><p className="mb-2 text-sm font-semibold uppercase tracking-widest text-pink-200">{product.categories?.name}</p><div className="glass rounded-3xl p-5"><h1 className="text-3xl font-bold">{product.name}</h1><p className="mt-2 leading-relaxed text-slate-100">{product.description}</p><strong className="mt-4 inline-block rounded-xl bg-white px-4 py-2 text-xl text-slate-900">{new Intl.NumberFormat(restaurant.locale,{style:"currency",currency:restaurant.currency}).format(product.price_cents/100)}</strong></div></div><div className="absolute bottom-6 right-5 flex flex-col gap-3"><button aria-label="Información del restaurante" onClick={()=>setOpen(true)} className="glass focus rounded-full p-3"><Info/></button><button aria-label="Activar o desactivar sonido" onClick={()=>setMuted(!muted)} className="glass focus rounded-full p-3">{muted?<VolumeX/>:<Volume2/>}</button></div></section>)}
 </main>
}
