import {describe,expect,it,vi} from "vitest";
import {automaticTranslationMap,translateFieldsToEnglish,translateTextsToEnglish} from "../src/lib/automatic-translation";

describe("traducción automática",()=>{
  it("no llama a servicios externos sin clave",async()=>{const fetcher=vi.fn();const result=await translateTextsToEnglish(["Tarta"],{apiKey:"",fetcher:fetcher as unknown as typeof fetch});expect(result).toEqual({status:"not_configured",value:["Tarta"]});expect(fetcher).not.toHaveBeenCalled()});
  it("envía lotes a DeepL con autenticación privada y conserva el orden",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({translations:[{text:"Cheesecake"},{text:"Creamy dessert"}]}),{status:200,headers:{"Content-Type":"application/json"}}));const result=await translateFieldsToEnglish({name:"Tarta de queso",description:"Postre cremoso"},{apiKey:"test:fx",fetcher:fetcher as unknown as typeof fetch});expect(result).toEqual({status:"translated",value:{name:"Cheesecake",description:"Creamy dessert"}});const[url,request]=fetcher.mock.calls[0];expect(url).toBe("https://api-free.deepl.com/v2/translate");expect(request.headers.Authorization).toBe("DeepL-Auth-Key test:fx");expect(JSON.parse(request.body)).toMatchObject({source_lang:"ES",target_lang:"EN-US",text:["Tarta de queso","Postre cremoso"]})});
  it("devuelve el original y permite guardar si el proveedor falla",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response("error",{status:503}));expect(await translateTextsToEnglish(["Entrantes"],{apiKey:"test",fetcher:fetcher as unknown as typeof fetch})).toEqual({status:"failed",value:["Entrantes"]})});
  it("omite campos vacíos",async()=>{expect(await translateFieldsToEnglish({name:"",description:"  "},{apiKey:"test"})).toEqual({status:"empty",value:{}})});
  it("evita traducciones antiguas si cambia el original y el proveedor falla",()=>{const current={en:{name:"Old name"},fr:{name:"Ancien"}};expect(automaticTranslationMap(current,{status:"failed",value:{name:"Nombre nuevo"}},true)).toEqual({fr:{name:"Ancien"}});expect(automaticTranslationMap(current,{status:"failed",value:{name:"Nombre"}},false)).toEqual(current)});
});
