import {describe,it,expect} from "vitest";
import {customizationSchema,resolveCustomization,type ProductCustomization} from "../src/lib/product-customization";
import {addCartItem,cartLineKey,changeCartQuantity,parseCart,updateCartNote} from "../src/lib/menu-cart";
import {priceOrderLines,pickupOrderSchema} from "../src/lib/pickup-orders";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const config:ProductCustomization={enabled:true,groups:[{id:id(1),name:"Frutas",min:8,max:8,options:Array.from({length:10},(_,i)=>({id:id(i+2),name:`Fruta ${i+1}`,imageUrl:null,priceCents:i===0?50:0,available:true}))}]};
const choose=(start=0,count=8)=>[{groupId:id(1),optionIds:config.groups[0].options.slice(start,start+count).map(o=>o.id)}];
describe("personalización por producto",()=>{
  it("allows exactly 8 of 10 and prices only selected extras",()=>{expect(resolveCustomization(config,choose()).extraCents).toBe(50);expect(resolveCustomization(config,choose(1)).extraCents).toBe(0)});
  it("rejects too few, too many, duplicated and unknown options",()=>{for(const selected of [choose(0,7),choose(0,9),[{groupId:id(1),optionIds:Array(8).fill(id(2))}],[{groupId:id(1),optionIds:[...choose()[0].optionIds.slice(1),id(100)]}]])expect(()=>resolveCustomization(config,selected)).toThrow()});
  it("rejects out of stock options after the cart was created",()=>{const updated=structuredClone(config);updated.groups[0].options[0].available=false;expect(()=>resolveCustomization(updated,choose())).toThrow("ya no está disponible")});
  it("supports normal products without making choices obligatory",()=>{expect(resolveCustomization(undefined)).toEqual({extraCents:0,options:[]});expect(()=>resolveCustomization({enabled:false,groups:[]},choose())).toThrow("ya no admite")});
  it("supports optional groups and validates every required group",()=>{const optional=structuredClone(config);optional.groups[0].min=0;expect(resolveCustomization(optional,[]).options).toEqual([]);expect(()=>resolveCustomization(config,[])).toThrow("Frutas")});
  it("validates maximums and unique group/option identities",()=>{expect(customizationSchema.safeParse(config).success).toBe(true);const invalid=structuredClone(config);invalid.groups[0].max=11;expect(customizationSchema.safeParse(invalid).success).toBe(false);invalid.groups[0].max=8;invalid.groups[0].options[0].id=id(1);expect(customizationSchema.safeParse(invalid).success).toBe(false)});
  it("keeps two salads with different ingredients separate",()=>{let cart=addCartItem([],id(100),choose());cart=addCartItem(cart,id(100),choose(1));expect(cart).toHaveLength(2);cart=addCartItem(cart,id(100),[{...choose()[0],optionIds:[...choose()[0].optionIds].reverse()}]);expect(cart.map(l=>l.quantity)).toEqual([2,1]);const key=cartLineKey(cart[1]);expect(changeCartQuantity(cart,key,-1)).toHaveLength(1);expect(updateCartNote(cart,key,"Sin hielo")[0].note).toBe("");expect(parseCart(JSON.stringify(cart))).toEqual(cart)});
  it("calculates snapshot names and totals on the server",()=>{const products=[{id:id(100),name:"Ensalada",price_cents:800,customization:config}];const items=priceOrderLines([{productId:id(100),quantity:2,note:"",selection:choose()},{productId:id(100),quantity:1,note:"",selection:choose(1)}],products,id(200));expect(items.map(i=>i.line_total_cents)).toEqual([1700,800]);products[0].customization.groups[0].name="Frutas nuevas";expect(items[0].selected_options[0].groupName).toBe("Frutas");products[0].customization.groups[0].name="Frutas"});
  it("drops forged client prices from the request",()=>{const result=pickupOrderSchema.parse({restaurantId:id(200),requestId:id(300),clientId:id(301),subtotal:1,lines:[{productId:id(100),quantity:1,note:"",price:1,selection:choose()}]});expect(result).not.toHaveProperty("subtotal");expect(result.lines[0]).not.toHaveProperty("price")});
  it("rejects unknown products and invalid quantities",()=>{expect(()=>priceOrderLines([{productId:id(100),quantity:1,note:"",selection:[]}],[],id(200))).toThrow();expect(pickupOrderSchema.safeParse({restaurantId:id(200),requestId:id(300),clientId:id(301),lines:[{productId:id(100),quantity:0}]}).success).toBe(false)});
});
