import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {LegalPage, LegalSection} from "@/components/legal/legal-page";
import {getLegalIdentity} from "@/lib/legal";

export const metadata:Metadata={title:"Condiciones del servicio | Menuly",robots:{index:false,follow:false}};

export default function TermsPage(){const identity=getLegalIdentity();if(!identity.complete)notFound();return <LegalPage title="Condiciones del servicio" summary="Regulan la contratación y el uso profesional de Menuly por restaurantes y negocios de hostelería." identity={identity}>
  <LegalSection title="1. Partes y ámbito"><p>Estas condiciones se celebran entre {identity.name}, proveedor de Menuly, y la persona o entidad que crea o contrata una cuenta. El servicio se dirige principalmente a profesionales. Si excepcionalmente contrata una persona consumidora, prevalecerán sus derechos legales irrenunciables.</p></LegalSection>
  <LegalSection title="2. El servicio"><p>Menuly permite gestionar y publicar una carta digital, productos, categorías, imágenes o vídeos, plantillas, QR, traducciones, carrito local y analíticas agregadas. El carrito no transmite comandas, no cobra al comensal y no sustituye un TPV ni un sistema de cocina.</p></LegalSection>
  <LegalSection title="3. Alta y cuenta"><p>La persona usuaria debe facilitar información veraz, custodiar sus credenciales y asignar correctamente los roles de su equipo. Es responsable de la actividad realizada desde sus accesos y debe comunicar cualquier uso no autorizado.</p></LegalSection>
  <LegalSection title="4. Prueba, planes y precios"><p>La prueba dura siete días y permite hasta tres productos y cinco categorías. Finalizado el plazo, la publicación de la carta puede suspenderse hasta registrar un pago válido. El Plan Carta cuesta 34,99 € al mes; la modalidad anual mostrada es un pago único con un ahorro aproximado del 18 %. El servicio Llave en mano cuesta 149,99 € al mes, ofrece el primer mes gratis e incluye hasta cuatro vídeos por cada una de un máximo de cinco categorías.</p><p className="mt-3">Los precios, impuestos aplicables, alcance final y periodicidad se confirmarán antes de contratar. Durante la beta, la activación y los pagos son manuales y no se realizan cargos automáticos.</p></LegalSection>
  <LegalSection title="5. Contenido y obligaciones del restaurante"><p>El restaurante garantiza que dispone de derechos y permisos sobre textos, marcas, imágenes y vídeos que incorpora. Debe mantener correctos precios, disponibilidad, ingredientes y alérgenos, cumplir la normativa alimentaria y no publicar contenido ilícito, engañoso, dañino o contrario a derechos de terceros.</p></LegalSection>
  <LegalSection title="6. Alérgenos y traducciones"><p>La información de alérgenos la proporciona y valida exclusivamente el restaurante. La traducción automática es una ayuda y puede contener errores: el restaurante debe revisar especialmente alérgenos, ingredientes, precios y textos con efectos legales o comerciales antes de publicar. La carta digital no sustituye la información obligatoria ni la confirmación del personal ante una alergia.</p></LegalSection>
  <LegalSection title="7. Licencia técnica"><p>El restaurante conserva la titularidad de su contenido y concede a Menuly una licencia no exclusiva, limitada a la vigencia del servicio, para alojarlo, adaptarlo técnicamente, traducirlo cuando se solicite y mostrarlo en su carta pública.</p></LegalSection>
  <LegalSection title="8. Uso aceptable"><p>No se permite comprometer la seguridad, superar deliberadamente límites técnicos, automatizar extracciones abusivas, distribuir malware, suplantar identidades ni usar la plataforma para fines ilícitos. Podrá limitarse o suspenderse el acceso cuando sea necesario para proteger el servicio, cumplir la ley o corregir un incumplimiento, informando cuando sea razonablemente posible.</p></LegalSection>
  <LegalSection title="9. Disponibilidad y soporte"><p>Se procura una disponibilidad continua, pero pueden producirse mantenimientos, fallos de red o incidencias de proveedores externos. El canal de soporte puede recibir avisos las 24 horas, todos los días; esto no constituye un plazo garantizado de respuesta o resolución salvo acuerdo de nivel de servicio por escrito.</p></LegalSection>
  <LegalSection title="10. Pagos, suspensión y baja"><p>La falta de pago permite suspender la carta pública y las funciones contratadas tras el vencimiento. La persona cliente puede solicitar la baja por {identity.email}. Antes de la eliminación definitiva podrá solicitar una copia razonable de sus contenidos en un formato disponible. Los datos se eliminarán conforme al proceso de papelera, obligaciones legales y copias de seguridad temporales.</p></LegalSection>
  <LegalSection title="11. Responsabilidad"><p>Cada parte responde de los daños directos y previsibles causados por sus incumplimientos. Menuly no responde de contenido o información incorrecta aportada por el restaurante, decisiones basadas en traducciones no revisadas, información de alérgenos no validada ni interrupciones ajenas a su control razonable. Estas limitaciones no afectan a responsabilidades que la ley no permita excluir.</p></LegalSection>
  <LegalSection title="12. Datos y confidencialidad"><p>El tratamiento de datos se rige por la política de privacidad y, cuando Menuly trate datos por cuenta del restaurante, por el acuerdo de encargo de tratamiento. Ambas partes mantendrán confidencial la información no pública recibida por razón del servicio.</p></LegalSection>
  <LegalSection title="13. Modificaciones"><p>Las condiciones pueden actualizarse por cambios legales, técnicos o del servicio. Los cambios relevantes se comunicarán con antelación razonable. Si alteran sustancialmente una contratación vigente, la persona cliente podrá resolverla antes de su entrada en vigor, sin perjuicio de importes ya devengados.</p></LegalSection>
  <LegalSection title="14. Ley y jurisdicción"><p>Se aplica la legislación española. Las controversias se someterán a los juzgados competentes según la normativa aplicable. Cuando exista una relación de consumo, se respetarán el derecho de desistimiento y cualquier otro derecho obligatorio que corresponda.</p></LegalSection>
</LegalPage>}
