"use client";

import Link from "next/link";
import {ArrowRight,Menu,X} from "lucide-react";
import {useState} from "react";

const links=[{href:"#producto",label:"Producto"},{href:"#como-funciona",label:"Cómo funciona"},{href:"#precios",label:"Precios"},{href:"#faq",label:"FAQs"},{href:"#contacto",label:"Contacto"}];

export function MarketingNav(){const[open,setOpen]=useState(false);return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/[.06] bg-[#0b0b0c]/95 text-[#f5f0eb] backdrop-blur-xl"><nav aria-label="Navegación principal" className="mx-auto flex h-[72px] max-w-[1344px] items-center justify-between gap-4 px-5 sm:px-8 lg:px-12"><Link href="#inicio" aria-label="Menuly · Inicio" className="text-xl font-extrabold tracking-[-.04em]">Menuly</Link><div className="hidden items-center gap-7 lg:flex">{links.map(link=><a key={link.href} href={link.href} className="text-sm font-medium text-[#a09890] transition hover:text-[#f5f0eb]">{link.label}</a>)}</div><div className="ml-auto hidden items-center gap-5 sm:flex"><Link href="/login" className="px-2 py-2 text-sm font-semibold text-[#f5f0eb] transition hover:text-[#d4943a]">Iniciar sesión</Link><Link href="/register" className="inline-flex items-center gap-2 rounded-[24px] bg-[#f5a623] px-5 py-2.5 text-sm font-bold text-[#0b0b0c] shadow-[0_0_18px_rgba(212,148,58,.28)] transition hover:-translate-y-0.5 hover:bg-[#f8b84a]">Crear mi carta<ArrowRight size={15}/></Link></div><button type="button" aria-label={open?"Cerrar menú":"Abrir menú"} aria-expanded={open} onClick={()=>setOpen(value=>!value)} className="grid size-10 shrink-0 place-items-center rounded-[12px] border border-white/15 text-[#f5f0eb] lg:hidden">{open?<X size={20}/>:<Menu size={20}/>}</button></nav>{open&&<div className="border-t border-white/[.06] bg-[#111112] px-5 pb-5 pt-3 lg:hidden"><div className="mx-auto grid max-w-7xl gap-1">{links.map(link=><a key={link.href} href={link.href} onClick={()=>setOpen(false)} className="rounded-[10px] px-4 py-3 text-sm text-[#a09890] hover:bg-white/[.05] hover:text-white">{link.label}</a>)}</div><div className="mx-auto mt-3 grid max-w-7xl grid-cols-2 gap-2 sm:hidden"><Link href="/login" className="rounded-[24px] border border-white/15 px-4 py-3 text-center text-sm font-semibold">Iniciar sesión</Link><Link href="/register" className="rounded-[24px] bg-[#f5a623] px-4 py-3 text-center text-sm font-bold text-[#0b0b0c]">Crear carta</Link></div></div>}</header>}
