"use client";

import Link from "next/link";
import {Menu,Play,X} from "lucide-react";
import {useState} from "react";

const links=[{href:"#producto",label:"Producto"},{href:"#como-funciona",label:"Cómo funciona"},{href:"#precios",label:"Precios"},{href:"#nosotros",label:"Quiénes somos"},{href:"#faq",label:"FAQ"},{href:"#contacto",label:"Contacto"}];

export function MarketingNav(){const[open,setOpen]=useState(false);return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#070912]/80 backdrop-blur-2xl"><nav aria-label="Navegación principal" className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 md:px-6"><Link href="#inicio" className="flex items-center gap-2 font-black tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-pink-500 shadow-lg shadow-violet-500/20"><Play size={16} fill="currentColor"/></span><span>Carta<span className="text-violet-300">Video</span></span></Link><div className="hidden items-center gap-1 lg:flex">{links.map(link=><a key={link.href} href={link.href} className="rounded-lg px-3 py-2 text-sm text-slate-400 transition hover:bg-white/[.06] hover:text-white">{link.label}</a>)}</div><div className="hidden items-center gap-2 sm:flex"><Link href="/login" className="rounded-xl px-4 py-2 text-sm font-semibold text-slate-300 hover:bg-white/[.06]">Acceder</Link><Link href="/register" className="rounded-xl bg-white px-4 py-2 text-sm font-bold text-slate-950 transition hover:bg-violet-100">Crear carta</Link></div><button type="button" aria-label={open?"Cerrar menú":"Abrir menú"} aria-expanded={open} onClick={()=>setOpen(value=>!value)} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 sm:hidden">{open?<X/>:<Menu/>}</button></nav>{open&&<div className="border-t border-white/10 bg-[#070912] px-4 pb-5 pt-3 sm:hidden"><div className="grid gap-1">{links.map(link=><a key={link.href} href={link.href} onClick={()=>setOpen(false)} className="rounded-xl px-4 py-3 text-sm text-slate-300 hover:bg-white/[.06]">{link.label}</a>)}</div><div className="mt-3 grid grid-cols-2 gap-2"><Link href="/login" className="rounded-xl border border-white/10 px-4 py-3 text-center text-sm font-semibold">Acceder</Link><Link href="/register" className="rounded-xl bg-white px-4 py-3 text-center text-sm font-bold text-slate-950">Crear carta</Link></div></div>}</header>}
