"use client";

import {useState} from "react";
import {AlertTriangle,Ban,Clock3} from "lucide-react";
import {processManualExpirations} from "@/app/superadmin/actions";

export function BillingOperations({overdue,dueSoon}:{overdue:number;dueSoon:number}){
  const[graceDays,setGraceDays]=useState(3);
  const[confirmed,setConfirmed]=useState(false);
  return <section className="mt-6 rounded-3xl border border-amber-400/20 bg-amber-400/[.04] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-300">Control de vencimientos</p><h2 className="mt-1 text-xl font-bold">Suscripciones manuales</h2><p className="mt-1 max-w-2xl text-sm text-slate-400">Primero marca los vencimientos como pago pendiente. La suspensión es una segunda acción explícita y solo afecta a pagos manuales fuera del periodo de cortesía.</p></div><div className="flex gap-2"><Counter label="Vencidos" value={overdue} danger/><Counter label="Próximos" value={dueSoon}/></div></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><form action={processManualExpirations} className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><input type="hidden" name="operation" value="mark"/><label className="text-sm font-medium">Días de cortesía<input name="grace_days" type="number" min="0" max="30" value={graceDays} onChange={event=>setGraceDays(Number(event.target.value))} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 p-3"/></label><p className="mt-2 text-xs text-slate-500">Cambia el estado a pago pendiente, pero el cliente todavía puede entrar.</p><button className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-amber-500 px-4 py-3 font-bold text-slate-950"><Clock3 size={18}/>Marcar vencidos</button></form>
      <form action={processManualExpirations} onSubmit={event=>{if(!confirmed||!window.confirm("¿Suspender las cuentas manuales vencidas fuera del periodo de cortesía?"))event.preventDefault()}} className="rounded-2xl border border-red-500/20 bg-red-500/[.04] p-4"><input type="hidden" name="operation" value="suspend"/><input type="hidden" name="grace_days" value={graceDays}/><label className="flex items-start gap-3 text-sm"><input name="confirm_suspension" value="yes" type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)} className="mt-1 h-4 w-4 accent-red-500"/><span><strong className="block">Confirmo el corte de acceso</strong><span className="mt-1 block text-xs text-slate-500">Ocultará la carta pública y bloqueará la edición hasta registrar un nuevo pago.</span></span></label><button disabled={!confirmed} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-3 font-bold disabled:cursor-not-allowed disabled:bg-slate-700"><Ban size={18}/>Suspender vencidos</button></form></div>
    {overdue===0&&<p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><AlertTriangle size={14}/>Actualmente no hay suscripciones manuales vencidas.</p>}
  </section>;
}

function Counter({label,value,danger=false}:{label:string;value:number;danger?:boolean}){return <div className={`min-w-20 rounded-xl border px-3 py-2 text-center ${danger?"border-red-500/20 bg-red-500/[.06]":"border-amber-400/20 bg-amber-400/[.06]"}`}><strong className="block text-xl tabular-nums">{value}</strong><span className="text-[10px] uppercase text-slate-400">{label}</span></div>}
