"use client";

import Link from "next/link";
import {Copy,ExternalLink,Mail,MessageCircle,ShieldAlert} from "lucide-react";
import {useState} from "react";
import {toast} from "sonner";
import {recordPaymentReminder} from "@/app/superadmin/actions";
import {paymentReminderChannelLabel,paymentReminderLinks,paymentReminderMessage,type PaymentReminderChannel} from "@/lib/payment-reminders";

export type CollectionItem={restaurantId:string;restaurantName:string;phone:string|null;email:string|null;periodEnd:string;state:"due_soon"|"overdue";suspended:boolean;lastContact:{createdAt:string;channel:PaymentReminderChannel}|null};

export function CollectionsInbox({items}:{items:CollectionItem[]}){
  return <section className="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">Seguimiento</p><h2 className="mt-1 text-xl font-bold">Cobros pendientes</h2><p className="mt-1 text-sm text-slate-400">Prepara el contacto y registra el canal. Ningún mensaje se envía automáticamente.</p><div className="mt-4 space-y-3">{items.map(item=><CollectionCard key={item.restaurantId} item={item}/>)}{!items.length&&<div className="rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-slate-500">No hay vencimientos próximos ni atrasados.</div>}</div></section>;
}

function CollectionCard({item}:{item:CollectionItem}){
  const[contact,setContact]=useState(item.lastContact);const message=paymentReminderMessage({restaurantName:item.restaurantName,periodEnd:item.periodEnd});const links=paymentReminderLinks({message,phone:item.phone,email:item.email});
  const track=async(channel:PaymentReminderChannel)=>{const form=new FormData();form.set("restaurant_id",item.restaurantId);form.set("channel",channel);form.set("period_end",item.periodEnd);await recordPaymentReminder(form);setContact({createdAt:new Date().toISOString(),channel})};
  const trackLink=(channel:"whatsapp"|"email")=>void track(channel).catch(()=>toast.error("Se abrió el contacto, pero no pudo registrarse"));
  const copy=async()=>{try{await navigator.clipboard.writeText(message);await track("copy");toast.success("Mensaje copiado y aviso registrado")}catch{toast.error("No se pudo copiar el mensaje")}};
  const date=new Intl.DateTimeFormat("es-ES",{dateStyle:"medium",timeZone:"Europe/Madrid"}).format(new Date(item.periodEnd));
  return <article className={`rounded-2xl border p-4 ${item.state==="overdue"?"border-red-400/25 bg-red-400/[.05]":"border-amber-400/20 bg-amber-400/[.05]"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-bold">{item.restaurantName}</h3><p className="mt-1 text-xs text-slate-400">{item.state==="overdue"?"Venció":"Vence"} el {date}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold uppercase ${item.state==="overdue"?"bg-red-500/15 text-red-300":"bg-amber-500/15 text-amber-300"}`}>{item.state==="overdue"?"Vencido":"Próximo"}</span></div>{item.suspended&&<p className="mt-3 flex items-center gap-1.5 text-xs font-semibold text-red-300"><ShieldAlert size={14}/>Acceso suspendido</p>}<p className="mt-3 rounded-xl bg-black/20 p-3 text-xs leading-relaxed text-slate-400">{message}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>void copy()} className="inline-flex items-center gap-1.5 rounded-lg border border-white/15 px-3 py-2 text-xs"><Copy size={14}/>Copiar</button>{links.whatsapp&&<a href={links.whatsapp} target="_blank" rel="noopener noreferrer" onClick={()=>trackLink("whatsapp")} className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold"><MessageCircle size={14}/>WhatsApp</a>}{links.email&&<a href={links.email} onClick={()=>trackLink("email")} className="inline-flex items-center gap-1.5 rounded-lg bg-violet-600 px-3 py-2 text-xs font-semibold"><Mail size={14}/>Correo</a>}<Link href={`/superadmin/restaurants/${item.restaurantId}`} className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300"><ExternalLink size={14}/>Gestionar</Link></div><p className="mt-3 text-[11px] text-slate-500">{contact?<>Último aviso preparado por {paymentReminderChannelLabel(contact.channel)} · {new Intl.DateTimeFormat("es-ES",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Madrid"}).format(new Date(contact.createdAt))}</>:"Todavía no se ha preparado ningún aviso."}</p>{!links.whatsapp&&!links.email&&<p className="mt-1 text-[11px] text-amber-300">Faltan teléfono y correo; puedes copiar el mensaje o completar los datos.</p>}</article>;
}
