import Link from "next/link";
import {Download,ReceiptText,Search} from "lucide-react";
import {filterLedgerPayments,monthlyPaymentClosure,paymentMethodLabels,paymentMethods,paymentRestaurant,safeLedgerMonth,type ManualPaymentRow,type PaymentMethodFilter} from "@/lib/manual-payment-ledger";
import {formatCurrencyTotals} from "@/lib/manual-finance";

export type FinanceFilters={q?:string;method?:string;from?:string;to?:string;month?:string};
function queryString(filters:FinanceFilters){const params=new URLSearchParams();for(const[key,value]of Object.entries(filters))if(value&&!(key==="method"&&value==="all"))params.set(key,value);const result=params.toString();return result?`?${result}`:""}

export function FinanceLedger({payments,filters}:{payments:ManualPaymentRow[];filters:FinanceFilters}){
  const month=safeLedgerMonth(filters.month);const closure=monthlyPaymentClosure(payments,month);const filtered=filterLedgerPayments(payments,filters);const visible=filtered.slice(0,30);const monthLabel=new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${month}-01T00:00:00Z`));const exportQuery=queryString(filters);
  return <section className="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-300">Libro privado</p><h2 className="mt-1 text-xl font-bold">Pagos manuales</h2><p className="mt-1 text-sm text-slate-400">Filtra el libro o prepara un cierre mensual operativo.</p></div><a href={`/api/superadmin/finance/export${exportQuery}`} className="inline-flex items-center justify-center gap-2 rounded-xl border border-emerald-400/25 bg-emerald-400/[.06] px-3 py-2 text-xs font-bold text-emerald-300 hover:bg-emerald-400/10"><Download size={15}/>Exportar CSV</a></div>
    <div className="mt-5 rounded-2xl border border-emerald-400/15 bg-emerald-400/[.04] p-4"><form method="get" className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><input type="hidden" name="q" value={filters.q??""}/><input type="hidden" name="method" value={filters.method??"all"}/><input type="hidden" name="from" value={filters.from??""}/><input type="hidden" name="to" value={filters.to??""}/><label><span className="mb-1 block text-xs font-semibold text-slate-400">Mes de cierre</span><input type="month" name="month" defaultValue={month} className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-sm"/></label><button className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold hover:bg-emerald-500">Ver cierre</button></form><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs capitalize text-slate-400">{monthLabel}</p><p className="mt-1 text-3xl font-black">{closure.formattedTotal}</p><p className="mt-1 text-xs text-slate-500">{closure.count===1?"1 pago confirmado":`${closure.count} pagos confirmados`}</p></div><div className="flex flex-wrap gap-2">{Object.entries(closure.methods).map(([method,count])=><span key={method} className="rounded-full bg-white/[.06] px-2.5 py-1 text-[10px] font-bold uppercase text-slate-300">{paymentMethodLabels[method as PaymentMethodFilter]??"Otro"}: {count}</span>)}{!Object.keys(closure.methods).length&&<span className="text-xs text-slate-500">Sin movimientos este mes.</span>}</div></div></div>
    <form method="get" className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-[1fr_auto_auto_auto_auto]"><input type="hidden" name="month" value={month}/><label className="sm:col-span-2 xl:col-span-1"><span className="mb-1 block text-xs font-semibold text-slate-400">Restaurante</span><span className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={16}/><input name="q" defaultValue={filters.q??""} maxLength={100} placeholder="Nombre o slug" className="w-full rounded-xl border border-white/10 bg-black/25 py-2.5 pl-9 pr-3 text-sm"/></span></label><label><span className="mb-1 block text-xs font-semibold text-slate-400">Método</span><select name="method" defaultValue={filters.method??"all"} className="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-sm">{paymentMethods.map(method=><option key={method} value={method}>{paymentMethodLabels[method]}</option>)}</select></label><label><span className="mb-1 block text-xs font-semibold text-slate-400">Desde</span><input type="date" name="from" defaultValue={filters.from??""} className="w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-sm"/></label><label><span className="mb-1 block text-xs font-semibold text-slate-400">Hasta</span><input type="date" name="to" defaultValue={filters.to??""} className="w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-sm"/></label><div className="flex items-end gap-2"><button className="flex-1 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-bold">Filtrar</button><Link href={`/superadmin/finance${queryString({month})}`} className="rounded-xl border border-white/10 px-3 py-2.5 text-sm">Limpiar</Link></div></form>
    <p className="mt-4 text-xs text-slate-500">{filtered.length===1?"1 pago encontrado":`${filtered.length} pagos encontrados`}{filtered.length>visible.length&&` · mostrando los ${visible.length} más recientes`}</p><div className="mt-3 space-y-3">{visible.map(payment=>{const restaurant=paymentRestaurant(payment.restaurants);return <article key={payment.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-bold">{restaurant?.name??"Restaurante eliminado"}</h3><p className="mt-1 text-xs text-slate-500">{paymentMethodLabels[payment.method as PaymentMethodFilter]??"Otro"} · {new Intl.DateTimeFormat("es-ES",{dateStyle:"medium"}).format(new Date(payment.paid_at))}</p></div><strong className="shrink-0 text-emerald-300">{formatCurrencyTotals({[payment.currency]:payment.amount_cents})}</strong></div><div className="mt-3 flex items-center justify-between gap-2 border-t border-white/[.07] pt-3 text-xs text-slate-500"><span>Cubre hasta {new Intl.DateTimeFormat("es-ES",{dateStyle:"medium"}).format(new Date(payment.period_end))}</span>{restaurant&&<Link href={`/superadmin/restaurants/${restaurant.id}`} className="font-bold text-violet-300">Gestionar →</Link>}</div></article>})}{!visible.length&&<div className="rounded-2xl border border-dashed border-white/15 p-8 text-center"><ReceiptText className="mx-auto text-slate-600"/><p className="mt-2 text-sm text-slate-500">No hay pagos con estos filtros.</p></div>}</div>
  </section>;
}
