import {CalendarClock,CircleDollarSign} from "lucide-react";
import {recordManualPayment} from "@/app/superadmin/actions";
import {defaultManualPeriodEnd,manualBillingState} from "@/lib/manual-billing";
import {PaymentReminder} from "@/components/superadmin/payment-reminder";

type Subscription={provider:string;status:string;current_period_end:string|null}|null;
type Payment={id:string;amount_cents:number;currency:string;method:string;paid_at:string;period_end:string;reference:string|null;notes:string|null};

const stateCopy={none:"Sin vencimiento",current:"Al corriente",due_soon:"Vence pronto",overdue:"Vencido"} as const;

export function ManualPaymentPanel({restaurantId,restaurantName,phone,email,currency,subscription,payments}:{restaurantId:string;restaurantName:string;phone:string|null;email:string|null;currency:string;subscription:Subscription;payments:Payment[]}){
  const billingState=manualBillingState(subscription?.current_period_end);
  const today=new Date().toISOString().slice(0,10);
  return <section className="mt-6 rounded-3xl border border-emerald-400/20 bg-emerald-400/[.04] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Cobro provisional</p><h2 className="mt-1 text-xl font-bold">Pagos por Bizum</h2><p className="mt-1 text-sm text-slate-400">Registrar un pago activa el plan, restaura el acceso y fija el próximo vencimiento.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${billingState==="overdue"?"bg-red-500/15 text-red-300":billingState==="due_soon"?"bg-amber-500/15 text-amber-300":"bg-emerald-500/15 text-emerald-300"}`}>{stateCopy[billingState]}</span></div>
    <div className="mt-5 grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(280px,.8fr)]"><form action={recordManualPayment} className="grid gap-3 rounded-2xl border border-white/10 bg-slate-950/50 p-4 sm:grid-cols-2"><input type="hidden" name="restaurant_id" value={restaurantId}/><PaymentField label="Importe"><div className="flex"><input name="amount" type="number" min="0.01" step="0.01" required placeholder="29.00" className="min-w-0 flex-1 rounded-l-xl border border-white/10 bg-slate-900 p-3"/><select name="currency" defaultValue={currency} aria-label="Moneda" className="rounded-r-xl border border-l-0 border-white/10 bg-slate-900 px-2"><option>EUR</option><option>USD</option><option>GBP</option><option>MXN</option></select></div></PaymentField><PaymentField label="Fecha del Bizum"><input name="paid_at" type="date" required defaultValue={today}/></PaymentField><PaymentField label="Acceso activo hasta"><input name="period_end" type="date" required defaultValue={defaultManualPeriodEnd()}/></PaymentField><PaymentField label="Referencia"><input name="reference" maxLength={100} placeholder="Concepto o teléfono"/></PaymentField><PaymentField label="Nota interna" wide><textarea name="notes" maxLength={500} placeholder="Información privada para soporte" className="min-h-20"/></PaymentField><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 font-bold sm:col-span-2"><CircleDollarSign size={18}/>Confirmar Bizum y activar plan</button></form>
      <div><h3 className="flex items-center gap-2 font-bold"><CalendarClock size={18}/>Historial</h3><div className="mt-3 max-h-80 space-y-2 overflow-y-auto pr-1">{payments.map(payment=><article key={payment.id} className="rounded-xl border border-white/10 bg-slate-950/50 p-3"><div className="flex items-center justify-between gap-3"><strong>{new Intl.NumberFormat("es-ES",{style:"currency",currency:payment.currency}).format(payment.amount_cents/100)}</strong><span className="text-xs uppercase text-emerald-300">{payment.method}</span></div><p className="mt-1 text-xs text-slate-400">Pagado {new Intl.DateTimeFormat("es-ES",{dateStyle:"medium"}).format(new Date(payment.paid_at))} · acceso hasta {new Intl.DateTimeFormat("es-ES",{dateStyle:"medium"}).format(new Date(payment.period_end))}</p>{payment.reference&&<p className="mt-2 text-xs text-slate-500">Ref: {payment.reference}</p>}{payment.notes&&<p className="mt-1 text-xs text-slate-500">{payment.notes}</p>}</article>)}{!payments.length&&<p className="rounded-xl border border-dashed border-white/10 p-4 text-sm text-slate-500">Todavía no hay pagos manuales.</p>}</div>{subscription?.current_period_end&&<PaymentReminder restaurantId={restaurantId} restaurantName={restaurantName} phone={phone} email={email} periodEnd={subscription.current_period_end}/>}</div>
    </div>
  </section>;
}

function PaymentField({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"sm:col-span-2":""}><span className="text-sm font-medium text-slate-300">{label}</span><div className="mt-1 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-white/10 [&_input]:bg-slate-900 [&_input]:p-3 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-slate-900 [&_textarea]:p-3">{children}</div></label>}
