import Link from "next/link";
import {CheckCircle2,Clock3,RefreshCw,TriangleAlert} from "lucide-react";
import {retryTrashCleanup} from "@/app/superadmin/operations-actions";
import {cleanupHealth,type CleanupRun} from "@/lib/operations-health";

type Details={processed?:unknown;purged?:unknown;failed?:unknown};

export function PlatformOperationsStatus({run,result}:{run:CleanupRun|null;result?:string}){
  const health=cleanupHealth(run);const details=(run?.details??{}) as Details;
  const healthy=health==="healthy";const failed=health==="failed";const title=healthy?"Tareas automáticas funcionando":failed?"La limpieza automática falló":health==="stale"?"La limpieza automática está atrasada":"Esperando la primera limpieza";
  const description=healthy&&run?`Última ejecución ${new Intl.DateTimeFormat("es-ES",{dateStyle:"medium",timeStyle:"short"}).format(new Date(run.created_at))}: ${Number(details.processed??0)} revisados, ${Number(details.purged??0)} eliminados y ${Number(details.failed??0)} fallidos.`:failed?"Los datos siguen protegidos. Puedes reintentar ahora o esperar a la siguiente ejecución diaria.":health==="stale"?"No hay una ejecución correcta durante las últimas 36 horas.":"Vercel ejecutará la tarea diariamente a las 03:15 UTC.";
  return <section className={`mt-5 rounded-2xl border p-4 ${healthy?"border-emerald-400/20 bg-emerald-400/[.06]":failed?"border-red-400/25 bg-red-400/[.08]":"border-amber-400/20 bg-amber-400/[.06]"}`} aria-label="Estado operativo"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-start gap-3">{healthy?<CheckCircle2 className="mt-0.5 shrink-0 text-emerald-400" size={21}/>:failed?<TriangleAlert className="mt-0.5 shrink-0 text-red-400" size={21}/>:<Clock3 className="mt-0.5 shrink-0 text-amber-300" size={21}/>}<div><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs leading-relaxed text-slate-400">{description}</p>{result&&<p className={`mt-2 text-xs font-semibold ${result==="completed"?"text-emerald-300":"text-red-300"}`}>{result==="completed"?"Reintento completado correctamente.":"El reintento volvió a fallar; el diagnóstico quedó registrado."}</p>}</div></div><div className="flex shrink-0 gap-2"><Link href="/superadmin/trash" className="inline-flex items-center justify-center rounded-xl border border-white/15 px-3 py-2 text-xs font-semibold hover:bg-white/5">Ver papelera</Link>{!healthy&&<form action={retryTrashCleanup}><button className="inline-flex items-center justify-center gap-1.5 rounded-xl bg-violet-600 px-3 py-2 text-xs font-bold hover:bg-violet-500"><RefreshCw size={14}/>Reintentar ahora</button></form>}</div></div></section>;
}
