import {setManagedCategoryVisibility,setManagedProductAvailability,updateManagedCategory,updateManagedProduct} from "@/app/superadmin/actions";

type Category={id:string;name:string;is_active:boolean};
type Product={id:string;name:string;description:string|null;price_cents:number;category_id:string;is_available:boolean;video_url:string|null};

export function SupportContentEditor({restaurantId,categories,products}:{restaurantId:string;categories:Category[];products:Product[]}){
  return <section className="mt-6 rounded-3xl border border-orange-400/15 bg-orange-50 p-5"><h2 className="text-xl font-bold">Edición de soporte</h2><p className="mt-1 text-sm text-slate-600">Corrige categorías y productos sin entrar en la cuenta del cliente. Cada cambio queda auditado.</p><div className="mt-5 grid gap-6 lg:grid-cols-2">
    <div><h3 className="text-sm font-bold uppercase tracking-wider text-slate-600">Categorías</h3><div className="mt-3 space-y-3">{categories.map(category=><article key={category.id} className="rounded-xl border border-stone-200 bg-white p-3"><form action={updateManagedCategory} className="flex gap-2"><input type="hidden" name="restaurant_id" value={restaurantId}/><input type="hidden" name="category_id" value={category.id}/><input name="name" defaultValue={category.name} aria-label={`Nombre de ${category.name}`} className="min-w-0 flex-1 rounded-lg border border-stone-200 bg-stone-100 px-3 py-2 text-sm"/><button className="rounded-lg bg-stone-100 px-3 py-2 text-xs font-semibold">Guardar</button></form><form action={setManagedCategoryVisibility} className="mt-2 flex items-center justify-between"><input type="hidden" name="restaurant_id" value={restaurantId}/><input type="hidden" name="category_id" value={category.id}/><input type="hidden" name="active" value={category.is_active?"false":"true"}/><span className="text-xs text-slate-500">{category.is_active?"Visible":"Oculta"}</span><button className="rounded-lg border border-stone-300 px-3 py-1.5 text-xs">{category.is_active?"Ocultar":"Mostrar"}</button></form></article>)}{!categories.length&&<p className="text-sm text-slate-500">No hay categorías.</p>}</div></div>
    <div><h3 className="text-sm font-bold uppercase tracking-wider text-slate-600">Productos</h3><div className="mt-3 space-y-3">{products.map(product=><article key={product.id} className="rounded-xl border border-stone-200 bg-white p-3"><form action={updateManagedProduct} className="grid grid-cols-[1fr_92px] gap-2"><input type="hidden" name="restaurant_id" value={restaurantId}/><input type="hidden" name="product_id" value={product.id}/><input name="name" defaultValue={product.name} aria-label="Nombre del producto" className="min-w-0 rounded-lg border border-stone-200 bg-stone-100 px-3 py-2 text-sm"/><input name="price" type="number" min="0" step="0.01" defaultValue={(product.price_cents/100).toFixed(2)} aria-label="Precio" className="rounded-lg border border-stone-200 bg-stone-100 px-3 py-2 text-sm"/><textarea name="description" defaultValue={product.description??""} aria-label="Descripción" className="col-span-2 min-h-16 rounded-lg border border-stone-200 bg-stone-100 px-3 py-2 text-sm"/><select name="category_id" defaultValue={product.category_id} aria-label="Categoría" className="rounded-lg border border-stone-200 bg-stone-100 px-3 py-2 text-sm">{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select><button className="rounded-lg bg-stone-100 px-3 py-2 text-xs font-semibold">Guardar</button></form><form action={setManagedProductAvailability} className="mt-2 flex items-center justify-between"><input type="hidden" name="restaurant_id" value={restaurantId}/><input type="hidden" name="product_id" value={product.id}/><input type="hidden" name="available" value={product.is_available?"false":"true"}/><span className="text-xs text-slate-500">{product.video_url?"Con vídeo":"Sin vídeo"} · {product.is_available?"Visible":"Oculto"}</span><button className="rounded-lg border border-stone-300 px-3 py-1.5 text-xs">{product.is_available?"Ocultar":"Mostrar"}</button></form></article>)}{!products.length&&<p className="text-sm text-slate-500">No hay productos.</p>}</div></div>
  </div></section>;
}
