import Link from "next/link";
import {AlertTriangle,CalendarClock,CircleDollarSign,Landmark,ReceiptText,TrendingUp,WalletCards} from "lucide-react";
import {requireSuperadmin} from "@/lib/superadmin";
import {formatCurrencyTotals,isFinancialRestaurant,manualFinanceSnapshot,type FinancePayment} from "@/lib/manual-finance";
import {manualBillingState} from "@/lib/manual-billing";

type Restaurant={id:string;name:string;slug:string;access_suspended?:boolean};
type Relation=Restaurant|Restaurant[]|null;
type Payment=FinancePayment&{id:string;method:string;period_end:string;restaurants:Relation};
type Subscription={restaurant_id:string;status:string;current_period_end:string|null;restaurants:Relation};
function related(value:Relation){return Array.isArray(value)?value[0]??null:value}
const methods:Record<string,string>={bizum:"Bizum",cash:"Efectivo",bank_transfer:"Transferencia",other:"Otro"};

export default async function FinancePage(){
  const {admin}=await requireSuperadmin();const[{data:paymentData,error:paymentError},{data:subscriptionData,error:subscriptionError}]=await Promise.all([admin.from("manual_payments").select("id,amount_cents,currency,method,paid_at,period_end,restaurants(id,name,slug)").order("paid_at",{ascending:false}).limit(500),admin.from("subscriptions").select("restaurant_id,status,current_period_end,restaurants(id,name,slug,access_suspended)").eq("provider","manual").order("current_period_end",{ascending:true})]);
  if(paymentError||subscriptionError)throw new Error(paymentError?.message??subscriptionError?.message);
  const payments=((paymentData??[]) as Payment[]).filter(item=>isFinancialRestaurant(related(item.restaurants)?.slug));const subscriptions=((subscriptionData??[]) as Subscription[]).filter(item=>isFinancialRestaurant(related(item.restaurants)?.slug));const snapshot=manualFinanceSnapshot(payments);const active=subscriptions.filter(item=>item.status==="active").length;const dueSoon=subscriptions.filter(item=>manualBillingState(item.current_period_end)==="due_soon").length;const overdue=subscriptions.filter(item=>manualBillingState(item.current_period_end)==="overdue").length;const peak=Math.max(1,...snapshot.months.map(month=>month.count));const upcoming=subscriptions.filter(item=>item.current_period_end).slice(0,8);
  return <main className="mx-auto max-w-7xl p-4 md:p-6"><div className="flex items-start gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-emerald-500/15 text-emerald-300"><Landmark size={23}/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Cobros provisionales</p><h1 className="mt-1 text-3xl font-extrabold">Finanzas manuales</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-400">Resumen de pagos registrados por Bizum, transferencia, efectivo u otros medios. Las monedas se mantienen separadas.</p></div></div>
    <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric icon={<CircleDollarSign/>} label="Cobrado este mes" value={formatCurrencyTotals(snapshot.current.totals)} wide/><Metric icon={<ReceiptText/>} label="Pagos este mes" value={String(snapshot.current.count)}/><Metric icon={<WalletCards/>} label="Planes activos" value={String(active)}/><Metric icon={<CalendarClock/>} label="Vencen pronto" value={String(dueSoon)} warning={dueSoon>0}/><Metric icon={<AlertTriangle/>} label="Vencidos" value={String(overdue)} danger={overdue>0}/></section>
    <section className="mt-6 rounded-3xl border border-white/10 bg-slate-950/50 p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-300">Últimos seis meses</p><h2 className="mt-1 text-xl font-bold">Evolución de cobros</h2><p className="mt-1 text-sm text-slate-400">La altura representa número de pagos; cada importe conserva su moneda.</p></div><div className="text-sm text-slate-400"><span className="font-semibold text-slate-200">Total histórico:</span> {formatCurrencyTotals(snapshot.allTime)}</div></div><div aria-label="Pagos mensuales" className="mt-5 flex min-h-52 items-end gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-black/20 px-3 pb-3 pt-6">{snapshot.months.map(month=><div key={month.key} className="flex min-w-20 flex-1 flex-col items-center justify-end gap-2"><span className="max-w-28 text-center text-[10px] leading-tight text-slate-400">{formatCurrencyTotals(month.totals)}</span><strong className="text-xs tabular-nums">{month.count}</strong><div title={`${month.label}: ${month.count} pagos`} className="w-full max-w-14 rounded-t-lg bg-gradient-to-t from-emerald-700 to-cyan-400" style={{height:`${Math.max(4,month.count/peak*105)}px`,opacity:month.count?1:.18}}/><span className="text-[10px] capitalize text-slate-500">{month.label}</span></div>)}</div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-300">Libro privado</p><h2 className="mt-1 text-xl font-bold">Pagos recientes</h2></div><TrendingUp className="text-emerald-300"/></div><div className="mt-4 space-y-3">{payments.slice(0,10).map(payment=>{const restaurant=related(payment.restaurants);return <article key={payment.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-bold">{restaurant?.name??"Restaurante eliminado"}</h3><p className="mt-1 text-xs text-slate-500">{methods[payment.method]??"Otro"} · {new Intl.DateTimeFormat("es-ES",{dateStyle:"medium"}).format(new Date(payment.paid_at))}</p></div><strong className="shrink-0 text-emerald-300">{formatCurrencyTotals({[payment.currency]:payment.amount_cents})}</strong></div><div className="mt-3 flex items-center justify-between gap-2 border-t border-white/[.07] pt-3 text-xs text-slate-500"><span>Cubre hasta {new Intl.DateTimeFormat("es-ES",{dateStyle:"medium"}).format(new Date(payment.period_end))}</span>{restaurant&&<Link href={`/superadmin/restaurants/${restaurant.id}`} className="font-bold text-violet-300">Gestionar →</Link>}</div></article>})}{!payments.length&&<Empty text="Todavía no hay pagos manuales registrados."/>}</div></section>
      <section className="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">Seguimiento</p><h2 className="mt-1 text-xl font-bold">Próximos vencimientos</h2><div className="mt-4 space-y-3">{upcoming.map(subscription=>{const restaurant=related(subscription.restaurants);const state=manualBillingState(subscription.current_period_end);return <article key={subscription.restaurant_id} className={`rounded-2xl border p-4 ${state==="overdue"?"border-red-400/20 bg-red-400/[.05]":state==="due_soon"?"border-amber-400/20 bg-amber-400/[.05]":"border-white/10 bg-black/20"}`}><div className="flex items-center justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-bold">{restaurant?.name??"Restaurante eliminado"}</h3><p className="mt-1 text-xs text-slate-500">{subscription.current_period_end?new Intl.DateTimeFormat("es-ES",{dateStyle:"medium"}).format(new Date(subscription.current_period_end)):"Sin vencimiento"}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${state==="overdue"?"bg-red-500/15 text-red-300":state==="due_soon"?"bg-amber-500/15 text-amber-300":"bg-emerald-500/10 text-emerald-300"}`}>{state==="overdue"?"Vencido":state==="due_soon"?"Próximo":"Al día"}</span></div>{restaurant&&<Link href={`/superadmin/restaurants/${restaurant.id}`} className="mt-3 inline-block text-xs font-bold text-violet-300">Abrir cobro →</Link>}</article>})}{!upcoming.length&&<Empty text="No hay suscripciones manuales con vencimiento."/>}</div></section></div>
  </main>;
}

function Metric({icon,label,value,wide=false,warning=false,danger=false}:{icon:React.ReactNode;label:string;value:string;wide?:boolean;warning?:boolean;danger?:boolean}){return <div className={`rounded-2xl border p-4 ${wide?"col-span-2 lg:col-span-1":""} ${danger?"border-red-400/25 bg-red-400/[.07]":warning?"border-amber-400/25 bg-amber-400/[.06]":"border-white/10 bg-slate-950/50"}`}><div className="flex items-center gap-2 text-[10px] font-semibold uppercase text-slate-500">{icon}{label}</div><p className="mt-3 break-words text-2xl font-black tabular-nums">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-slate-500">{text}</div>}
