import {BackButton} from "@/components/ui/back-button";
import {QrCard} from "@/components/dashboard/qr-card";
import {activeRestaurant} from "@/lib/permissions";
import {closeTableSession,createDiningTable,extendTableSession,openTableSession,setDiningTableActive} from "@/app/dashboard/ordering/actions";

type Session={id:string;table_id:string;status:string;expires_at:string;started_at:string};

export default async function TablesPage(){
  const{supabase,restaurant}=await activeRestaurant();
  if(!restaurant.ordering_enabled)return <Unavailable/>;
  const now=new Date().toISOString();
  await supabase.from("table_sessions").update({status:"expired",closed_at:now}).eq("restaurant_id",restaurant.id).eq("status","open").lte("expires_at",now);
  const[{data:tables,error},{data:sessions}]=await Promise.all([
    supabase.from("restaurant_tables").select("id,name,public_code,is_active,sort_order").eq("restaurant_id",restaurant.id).order("sort_order").order("created_at"),
    supabase.from("table_sessions").select("id,table_id,status,started_at,expires_at").eq("restaurant_id",restaurant.id).eq("status","open"),
  ]);if(error)throw new Error(error.message);
  const byTable=new Map((sessions??[]).map(item=>[item.table_id,item as Session]));const root=process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000";
  return <main className="mx-auto max-w-6xl p-4 md:p-6"><BackButton fallback="/dashboard"/><div className="mt-5 flex flex-col gap-4 border-b border-stone-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-orange-700">Menuly Pedidos</p><h1 className="mt-1 text-3xl font-extrabold">Mesas y códigos QR</h1><p className="mt-2 text-sm text-slate-600">Abre una sesión cuando se sienten los clientes. Cada sesión dura 90 minutos.</p></div><form action={createDiningTable} className="flex gap-2"><input name="name" required maxLength={40} placeholder="Ej. Mesa 8" className="min-w-0 border border-stone-300 bg-white px-3 py-2.5"/><button className="bg-orange-600 px-4 py-2.5 text-sm font-bold text-white">Añadir mesa</button></form></div>
    <div className="mt-6 grid gap-5 md:grid-cols-2">{(tables??[]).map(table=>{const session=byTable.get(table.id);const url=`${root}/r/${restaurant.slug}?table=${table.public_code}`;return <article key={table.id} className={`border bg-white p-5 shadow-sm ${table.is_active?"border-stone-200":"border-stone-300 opacity-65"}`}><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{table.name}</h2><p className={`mt-1 text-xs font-semibold ${session?"text-emerald-700":"text-slate-500"}`}>{session?`Abierta hasta ${new Intl.DateTimeFormat("es-ES",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Madrid"}).format(new Date(session.expires_at))}`:table.is_active?"Cerrada · no acepta pedidos":"Desactivada"}</p></div><span className={`px-2 py-1 text-[10px] font-bold uppercase ${session?"bg-emerald-100 text-emerald-800":"bg-stone-100 text-slate-600"}`}>{session?"En servicio":"Cerrada"}</span></div><div className="mt-4 flex flex-wrap gap-2">{table.is_active&&!session&&<form action={openTableSession}><input type="hidden" name="table_id" value={table.id}/><button className="bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Abrir 90 min</button></form>}{session&&<><form action={extendTableSession}><input type="hidden" name="session_id" value={session.id}/><button className="border border-stone-300 px-3 py-2 text-xs font-bold">Añadir 90 min</button></form><form action={closeTableSession}><input type="hidden" name="session_id" value={session.id}/><button className="bg-slate-900 px-3 py-2 text-xs font-bold text-white">Cerrar mesa</button></form></>}<form action={setDiningTableActive}><input type="hidden" name="table_id" value={table.id}/><input type="hidden" name="active" value={table.is_active?"false":"true"}/><button className="border border-stone-300 px-3 py-2 text-xs">{table.is_active?"Desactivar":"Activar"}</button></form></div><details className="mt-4 border-t border-stone-200 pt-4"><summary className="cursor-pointer text-sm font-bold text-orange-700">Ver y descargar QR</summary><div className="mt-4"><QrCard url={url} fileName={`menuly-${restaurant.slug}-${table.name.toLowerCase().replaceAll(" ","-")}.png`}/></div></details></article>})}{!tables?.length&&<div className="border border-dashed border-stone-300 bg-white p-10 text-center text-sm text-slate-500 md:col-span-2">Añade la primera mesa para generar su QR.</div>}</div>
  </main>;
}

function Unavailable(){return <main className="mx-auto max-w-3xl p-6"><BackButton fallback="/dashboard"/><section className="mt-6 border border-stone-200 bg-white p-8 text-center"><h1 className="text-2xl font-bold">Menuly Pedidos no está activo</h1><p className="mt-2 text-sm text-slate-600">Este módulo pertenece al plan de 59,99 € e incluye mesas, comandas y pantalla de cocina.</p></section></main>}
