"use client";
import {useState,useTransition} from "react";
import Link from "next/link";
import {toast} from "sonner";
import {saveOrderSettings} from "@/app/dashboard/ordering/settings-actions";
import type {OrderSettings as Settings} from "@/lib/order-settings";
export function OrderSettings({initial,canOrder}:{initial:Settings;canOrder:boolean}){
  const [mode,setMode]=useState(canOrder?initial.customer_order_mode:"menu_only");const [timing,setTiming]=useState(initial.payment_timing);const [hours,setHours]=useState(initial.opening_hours);const [busy,start]=useTransition();
  return <form className="order-settings-form" action={form=>start(async()=>{try{await saveOrderSettings(form);if(typeof BroadcastChannel!=="undefined"){const channel=new BroadcastChannel("menuly:order-settings");channel.postMessage("saved");channel.close()}toast.success("Configuración guardada")}catch(error){toast.error(error instanceof Error?error.message:"No se pudo guardar")}})}>
    <fieldset disabled={busy}><legend>Qué pueden hacer tus clientes</legend><p>El QR de cada mesa abre la carta. Tú decides si permite enviar pedidos.</p>
      <div className="order-settings-choices">{[['menu_only','Solo consultar la carta','Los clientes ven productos y precios. El personal toma las comandas.'],['table_orders','Pedir desde la mesa','El cliente envía su selección a cocina desde el QR de su mesa.']].map(([value,title,description])=><label key={value} data-selected={mode===value}><input type="radio" name="customer_order_mode" value={value} checked={mode===value} disabled={value==='table_orders'&&!canOrder} onChange={()=>setMode(value as Settings['customer_order_mode'])}/><span><strong>{title}</strong><small>{description}</small></span></label>)}</div>
      {!canOrder&&<p>Los pedidos requieren Menuly Comandas. Puedes usar los QR de mesa para consultar la carta.</p>}
    </fieldset>
    <fieldset disabled={busy||mode==='menu_only'}><legend>Cuándo paga el cliente</legend><p>El cobro se realiza en vuestro TPV. Menuly organiza el pedido y registra su estado.</p>
      <div className="order-settings-choices">{[['before','Antes de preparar','Recibe un número, se acerca a pagar y el personal confirma el pago en Cocina para empezar.'],['after','Después de preparar o servir','El pedido entra directamente en cocina. El personal confirma el pago cuando se cobre en el TPV.']].map(([value,title,description])=><label key={value} data-selected={timing===value}><input type="radio" name="payment_timing" value={value} checked={timing===value} onChange={()=>setTiming(value as Settings['payment_timing'])}/><span><strong>{title}</strong><small>{description}</small></span></label>)}</div>
    </fieldset>
    {mode==='menu_only'&&<input type="hidden" name="payment_timing" value={timing}/>}
    <fieldset disabled={busy}><legend>Horario automático de las mesas</legend><p>Las mesas aceptan pedidos durante estas franjas y se cierran al terminar. Si el cierre es anterior a la apertura, termina al día siguiente. La misma hora de apertura y cierre equivale a 24 horas.</p><label>Zona horaria<input name="timezone" defaultValue={initial.timezone} required placeholder="Europe/Madrid"/></label><input type="hidden" name="opening_hours" value={JSON.stringify(hours)}/>
      <div className="order-hours">{[1,2,3,4,5,6,0].map(day=>{const entry=hours.find(h=>h.day===day)!;const change=(periods:typeof entry.periods)=>setHours(current=>current.map(h=>h.day===day?{...h,periods}:h));return <div key={day} className="order-hours-day"><label><input type="checkbox" checked={!!entry.periods.length} onChange={e=>change(e.target.checked?[{start:'12:00',end:'23:00'}]:[])}/>{['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'][day]}</label><div>{entry.periods.length?entry.periods.map((period,index)=><div className="order-hours-period" key={index}><input type="time" aria-label={`Apertura ${day} franja ${index+1}`} required value={period.start} onChange={e=>change(entry.periods.map((p,i)=>i===index?{...p,start:e.target.value}:p))}/><span>—</span><input type="time" aria-label={`Cierre ${day} franja ${index+1}`} required value={period.end} onChange={e=>change(entry.periods.map((p,i)=>i===index?{...p,end:e.target.value}:p))}/><button type="button" aria-label={`Quitar franja ${index+1} del día ${day}`} onClick={()=>change(entry.periods.filter((_,i)=>i!==index))}>×</button></div>):<span>Cerrado</span>}{entry.periods.length>0&&entry.periods.length<3&&<button type="button" onClick={()=>change([...entry.periods,{start:'19:00',end:'23:00'}])}>Añadir franja</button>}</div></div>})}</div>
    </fieldset>
    <fieldset disabled={busy}><legend>Acceso y servicio</legend><p>Los pedidos solo se envían desde los QR de mesa, dentro del horario. El enlace público general permite consultar la carta.</p><label className="order-settings-pause"><input type="checkbox" name="customer_orders_paused" defaultChecked={initial.customer_orders_paused}/><span><strong>Pausar nuevos pedidos</strong><small>Los pedidos ya recibidos siguen disponibles en cocina.</small></span></label><Link className="workspace-button" href="/dashboard/tables">Gestionar mesas y descargar QR</Link></fieldset>
    <footer><span>Los cambios de pago se aplican a pedidos nuevos.</span><button disabled={busy} className="workspace-button workspace-button-primary">{busy?'Guardando…':'Guardar configuración'}</button></footer>
  </form>;
}
