"use client";
import {useEffect,useState,useTransition} from "react";
import type {KitchenOrder} from "@/lib/kitchen-orders";
import {confirmPickupPayment} from "@/app/dashboard/ordering/pickup-actions";
export function PickupCashier({initialOrders,currency}:{initialOrders:KitchenOrder[];currency:string}){
  const[orders,setOrders]=useState(initialOrders);const[search,setSearch]=useState("");const[error,setError]=useState("");const[busy,start]=useTransition();
  useEffect(()=>{let disposed=false;let inFlight=false;const refresh=async()=>{if(inFlight)return;inFlight=true;try{const response=await fetch("/api/dashboard/pickup-orders",{cache:"no-store"});const data=await response.json();if(!response.ok||!data.orders)throw new Error();if(!disposed){setOrders(data.orders);setError("")}}catch{if(!disposed)setError("No se pudo sincronizar caja. Se reintentará automáticamente.")}finally{inFlight=false}};const timer=setInterval(()=>void refresh(),3000);return()=>{disposed=true;clearInterval(timer)}},[]);
  const money=(cents:number)=>new Intl.NumberFormat("es-ES",{style:"currency",currency}).format(cents/100);
  return <main className="mx-auto max-w-6xl p-4 md:p-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">Caja · Recogidas</h1><p className="mt-1 text-sm">Confirma el cobro después de recibir el pago y entregar el pedido.</p></div><nav className="flex gap-4 text-sm"><a href="/operaciones/comandero">Comandero</a><a href="/operaciones/cocina">Cocina</a></nav></header><label className="my-5 block text-sm">Buscar número de pedido<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ej. A42B7C91" className="mt-2 block w-full rounded-lg border p-3"/></label>{error&&<p role="alert" className="mb-4 text-red-700">{error}</p>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{orders.filter(o=>o.number.includes(search.trim().replace(/^#/,"").toUpperCase())).map(order=><article key={order.id} className="rounded-xl border border-stone-200 bg-white p-4"><div className="flex justify-between"><h2 className="font-bold">#{order.number}</h2><strong>{money(order.subtotalCents)}</strong></div><p className="mt-2 text-sm">{{pending:"Recibido",accepted:"Aceptado",preparing:"Preparando",ready:"Listo para recoger",delivered:"Entregado",cancelled:"Cancelado",rejected:"Rechazado"}[order.status]} · {order.paymentStatus==="paid"?"Pagado":"Sin cobrar"}</p><ul className="my-4 space-y-3">{order.items.map(item=><li key={item.id}><strong className="text-sm">{item.quantity} × {item.name}</strong>{item.options?.map(o=><p className="text-xs text-slate-600" key={o.optionId}>{o.groupName}: {o.name}</p>)}{item.note&&<p className="text-xs font-medium">Nota: {item.note}</p>}</li>)}</ul>{order.customerNote&&<p className="mb-3 text-sm">{order.customerNote}</p>}{order.status==="ready"&&order.paymentStatus!=="paid"&&<button disabled={busy} className="min-h-11 w-full rounded-lg bg-emerald-800 px-4 py-3 font-semibold text-white disabled:opacity-50" onClick={()=>{if(confirm(`¿Has cobrado ${money(order.subtotalCents)} y entregado el pedido #${order.number}?`))start(async()=>{try{await confirmPickupPayment(order.id);setOrders(list=>list.map(o=>o.id===order.id?{...o,status:"delivered",paymentStatus:"paid"}:o));setError("")}catch(e){setError(e instanceof Error?e.message:"No se pudo confirmar")}})}}>Confirmar cobrado y entregado</button>}</article>)}</div>{!orders.length&&<p className="py-12 text-center">No hay pedidos para recoger en las últimas 24 horas.</p>}</main>;
}
