import Link from "next/link";
import {MessageSquareText} from "lucide-react";
import {requireSuperadmin} from "@/lib/superadmin";
import {updateRestaurantFeedback} from "@/app/superadmin/actions";

const categoryLabels:Record<string,string>={improvement:"Mejora",feature:"Nueva función",problem:"Problema",remove:"Quitar algo",other:"Otro"};
const statusLabels:Record<string,string>={new:"Nueva",reviewed:"Revisada",planned:"Planificada",closed:"Cerrada"};
type FeedbackRow={id:string;restaurant_id:string;category:string;message:string;status:string;admin_note:string|null;created_at:string;restaurants:{name?:string;slug?:string}|{name?:string;slug?:string}[]|null};

export default async function FeedbackPage(){
  const{admin}=await requireSuperadmin();const{data,error}=await admin.from("restaurant_feedback").select("id,restaurant_id,category,message,status,admin_note,created_at,restaurants(name,slug)").order("created_at",{ascending:false}).limit(200);if(error)throw new Error(error.message);
  const rows=(data??[]) as FeedbackRow[];const pending=rows.filter(item=>item.status==="new").length;
  return <main className="mx-auto max-w-6xl p-4 md:p-6"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-stone-200 pb-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-700">Voz del cliente</p><h1 className="mt-1 text-2xl font-extrabold">Sugerencias</h1><p className="mt-1 text-sm text-slate-600">{pending} nueva{pending===1?"":"s"} · {rows.length} recibida{rows.length===1?"":"s"}</p></div></div>
    <div className="mt-6 grid gap-4">{rows.map(item=>{const restaurant=Array.isArray(item.restaurants)?item.restaurants[0]:item.restaurants;return <article key={item.id} className="border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="bg-orange-100 px-2 py-1 text-xs font-bold text-orange-800">{categoryLabels[item.category]??item.category}</span><span className="bg-stone-100 px-2 py-1 text-xs font-bold text-stone-700">{statusLabels[item.status]??item.status}</span></div><h2 className="mt-3 font-bold">{restaurant?.name??"Restaurante eliminado"}</h2><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat("es-ES",{dateStyle:"long",timeStyle:"short"}).format(new Date(item.created_at))}</p></div>{restaurant?.slug&&<Link href={`/r/${restaurant.slug}`} target="_blank" className="text-xs font-bold text-orange-700 hover:underline">Ver carta</Link>}</div><p className="mt-4 whitespace-pre-wrap text-sm leading-relaxed text-slate-800">{item.message}</p>
      <form action={updateRestaurantFeedback} className="mt-5 grid gap-3 border-t border-stone-200 pt-4 sm:grid-cols-[180px_1fr_auto]"><input type="hidden" name="feedback_id" value={item.id}/><input type="hidden" name="restaurant_id" value={item.restaurant_id}/><select name="status" defaultValue={item.status} aria-label="Estado" className="border border-stone-300 bg-white p-2.5 text-sm"><option value="new">Nueva</option><option value="reviewed">Revisada</option><option value="planned">Planificada</option><option value="closed">Cerrada</option></select><input name="admin_note" defaultValue={item.admin_note??""} maxLength={2000} placeholder="Nota interna opcional" className="min-w-0 border border-stone-300 p-2.5 text-sm"/><button className="bg-slate-900 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-700">Guardar</button></form></article>})}{!rows.length&&<div className="grid place-items-center border border-dashed border-stone-300 bg-white p-12 text-center"><MessageSquareText className="text-stone-400"/><p className="mt-3 text-sm text-slate-500">Todavía no hay sugerencias.</p></div>}</div>
  </main>;
}
