import Link from "next/link";
import {Activity,Building2,CalendarClock,CircleDollarSign,Download,FilePenLine,KeyRound,Search,ServerCog} from "lucide-react";
import {requireSuperadmin} from "@/lib/superadmin";
import {auditGroups,isAuditGroup,type AuditGroup,type AuditTone} from "@/lib/audit-events";
import {activityItems,safeActivityDate,type AuditActivityRow} from "@/lib/audit-activity";

const labels:Record<AuditGroup,string>={all:"Todo",restaurants:"Restaurantes",access:"Acceso",payments:"Pagos",content:"Carta",system:"Sistema"};
const icons={all:Activity,restaurants:Building2,access:KeyRound,payments:CircleDollarSign,content:FilePenLine,system:ServerCog};
const tones:Record<AuditTone,string>={neutral:"border-stone-200 bg-stone-505",success:"border-emerald-400/20 bg-emerald-400/[.05]",warning:"border-amber-400/20 bg-amber-400/[.05]",danger:"border-red-400/20 bg-red-400/[.06]"};

function queryString(values:{group?:string;q?:string;from?:string;to?:string}){const params=new URLSearchParams();for(const[key,value]of Object.entries(values))if(value&&!(key==="group"&&value==="all"))params.set(key,value);const result=params.toString();return result?`?${result}`:""}

export default async function ActivityPage({searchParams}:{searchParams:Promise<{group?:string;q?:string;from?:string;to?:string}>}){
  const params=await searchParams;const group=isAuditGroup(params.group)?params.group:"all";const q=String(params.q??"").trim().slice(0,100);const from=safeActivityDate(params.from);const to=safeActivityDate(params.to,true);const {admin}=await requireSuperadmin();
  let request=admin.from("superadmin_audit_log").select("id,actor_user_id,restaurant_id,action,details,created_at,restaurants(name,slug)").order("created_at",{ascending:false}).limit(500);if(from)request=request.gte("created_at",from);if(to)request=request.lte("created_at",to);
  const {data,error}=await request;if(error)throw new Error(error.message);
  const filtered=activityItems((data??[]) as AuditActivityRow[],{group,q});const visible=filtered.slice(0,150);const exportQuery=queryString({group,q,from:params.from,to:params.to});
  return <main className="mx-auto max-w-5xl p-4 md:p-6"><div className="flex items-start gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-orange-100 text-orange-700"><Activity size={23}/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-700">Auditoría privada</p><h1 className="mt-1 text-3xl font-extrabold">Actividad de la plataforma</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-600">Cambios de soporte, pagos y tareas automáticas. Los respaldos y diagnósticos sensibles nunca se muestran aquí.</p></div></div>
    <form className="mt-6 grid gap-3 rounded-2xl border border-stone-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-[1fr_auto_auto_auto]" method="get"><input type="hidden" name="group" value={group}/><label className="sm:col-span-2 lg:col-span-1"><span className="mb-1 block text-xs font-semibold text-slate-600">Restaurante o evento</span><span className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={16}/><input name="q" defaultValue={q} maxLength={100} placeholder="Ej. Illegal, pago o limpieza" className="w-full rounded-xl border border-stone-200 bg-white py-2.5 pl-9 pr-3 text-sm outline-none focus:border-orange-400"/></span></label><label><span className="mb-1 block text-xs font-semibold text-slate-600">Desde</span><input type="date" name="from" defaultValue={params.from??""} className="w-full rounded-xl border border-stone-200 bg-white px-3 py-2 text-sm"/></label><label><span className="mb-1 block text-xs font-semibold text-slate-600">Hasta</span><input type="date" name="to" defaultValue={params.to??""} className="w-full rounded-xl border border-stone-200 bg-white px-3 py-2 text-sm"/></label><div className="flex items-end gap-2"><button className="flex-1 rounded-xl bg-orange-600 px-4 py-2.5 text-sm font-bold hover:bg-orange-600">Filtrar</button><Link href="/superadmin/activity" className="rounded-xl border border-stone-200 px-3 py-2.5 text-sm hover:bg-stone-100">Limpiar</Link></div></form>
    <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><nav className="flex gap-2 overflow-x-auto pb-1" aria-label="Filtrar actividad">{auditGroups.map(item=>{const Icon=icons[item];return <Link key={item} href={`/superadmin/activity${queryString({group:item,q,from:params.from,to:params.to})}`} aria-current={group===item?"page":undefined} className={`inline-flex shrink-0 items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-bold ${group===item?"bg-orange-600 text-white":"border border-stone-200 bg-white text-slate-700 hover:bg-stone-100"}`}><Icon size={14}/>{labels[item]}</Link>})}</nav><a href={`/api/superadmin/activity/export${exportQuery}`} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl border border-emerald-400/25 bg-emerald-400/[.06] px-3 py-2 text-xs font-bold text-emerald-800 hover:bg-emerald-400/10"><Download size={15}/>Exportar CSV</a></div>
    <p className="mt-3 text-xs text-slate-500">{filtered.length===1?"1 evento encontrado":`${filtered.length} eventos encontrados`}{filtered.length>visible.length&&` · mostrando los ${visible.length} más recientes`}</p>
    <section className="mt-3 space-y-3" aria-label="Eventos recientes">{visible.map(({row,event,restaurant,restaurantName})=><article key={row.id} className={`rounded-2xl border p-4 ${tones[event.tone]}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{event.title}</h2><span className="rounded-full bg-stone-100 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-slate-600">{labels[event.group]}</span></div><p className="mt-1 text-sm leading-relaxed text-slate-600">{event.description}</p>{restaurantName&&<p className="mt-2 truncate text-xs font-semibold text-slate-700">{restaurantName}</p>}</div><CalendarClock className="mt-0.5 shrink-0 text-slate-500" size={17}/></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-stone-200 pt-3 text-[11px] text-slate-500"><span>{new Intl.DateTimeFormat("es-ES",{dateStyle:"medium",timeStyle:"short"}).format(new Date(row.created_at))} · {row.actor_user_id?"Superadmin":"Sistema"}</span>{row.restaurant_id&&restaurant&&<Link href={`/superadmin/restaurants/${row.restaurant_id}`} className="font-bold text-orange-700 hover:text-orange-800">Abrir restaurante →</Link>}</div></article>)}{!visible.length&&<div className="rounded-3xl border border-dashed border-stone-300 p-10 text-center"><Activity className="mx-auto text-slate-600" size={32}/><h2 className="mt-3 font-bold">No hay actividad con estos filtros</h2><p className="mt-1 text-sm text-slate-500">Prueba con otro restaurante, categoría o rango de fechas.</p></div>}</section>
  </main>;
}
