import Link from "next/link";
import {BarChart3,Eye,Languages,MousePointerClick,Play,Share2,ShoppingBag,Store,UtensilsCrossed} from "lucide-react";
import {requireSuperadmin} from "@/lib/superadmin";
import {analyticsPeriodStart,summarizePlatformAnalytics,type PlatformAnalyticsRow} from "@/lib/platform-analytics";

const periodLabels={"7":"7 días","30":"30 días","90":"90 días","365":"1 año",all:"Todo"};

export default async function PlatformAnalyticsPage({searchParams}:{searchParams:Promise<{period?:string}>}){
  const{period:requested}=await searchParams;const{period,from}=analyticsPeriodStart(requested);const{admin}=await requireSuperadmin();let query=admin.from("menu_analytics_daily").select("event_date,event_type,event_count,restaurant_id,product_id,locale,restaurants(name,slug),products(name,video_url,video_path)").order("event_date",{ascending:true}).limit(10000);if(from)query=query.gte("event_date",from);const{data,error}=await query;if(error)throw new Error(error.message);const summary=summarizePlatformAnalytics((data??[]) as PlatformAnalyticsRow[]);const peak=Math.max(1,...summary.days.map(day=>Math.max(day.menuViews,day.productViews,day.videoPlays,day.cartAdds)));const languageTotal=summary.languages.es+summary.languages.en+summary.languages.other;
  return <main className="mx-auto max-w-7xl p-4 md:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Rendimiento global</p><h1 className="mt-1 text-3xl font-extrabold">Analíticas de la plataforma</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Actividad agregada de todas las cartas, sin cookies, IP ni identificadores de visitante.</p></div><nav aria-label="Periodo de analíticas" className="flex flex-wrap gap-1 rounded-xl border border-white/10 bg-black/20 p-1">{Object.entries(periodLabels).map(([value,label])=><Link key={value} href={`/superadmin/analytics?period=${value}`} className={`rounded-lg px-3 py-2 text-xs font-semibold ${period===value?"bg-cyan-400 text-slate-950":"text-slate-400 hover:bg-white/10"}`}>{label}</Link>)}</nav></div>
    <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-6"><Metric icon={<Eye/>} label="Visitas a cartas" value={summary.totals.menuViews}/><Metric icon={<UtensilsCrossed/>} label="Productos vistos" value={summary.totals.productViews}/><Metric icon={<Play/>} label="Vídeos reproducidos" value={summary.totals.videoPlays}/><Metric icon={<ShoppingBag/>} label="Añadidos al carrito" value={summary.totals.cartAdds}/><Metric icon={<Share2/>} label="Compartidos" value={summary.totals.shares}/><Metric icon={<MousePointerClick/>} label="Contactos" value={summary.totals.contactClicks}/></section>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Rate label="Productos por visita" value={summary.rates.productsPerVisit} suffix=""/><Rate label="Reproducción de vídeo" value={summary.rates.videoPlayRate}/><Rate label="Producto → carrito" value={summary.rates.cartRate}/><Rate label="Visita → contacto" value={summary.rates.contactRate}/></section>
    <section className="mt-6 rounded-3xl border border-white/10 bg-slate-950/50 p-5"><div className="flex items-center gap-2"><BarChart3 className="text-cyan-300" size={20}/><div><h2 className="font-bold">Actividad diaria</h2><p className="text-xs text-slate-500">Visitas, productos, vídeos y carrito</p></div></div><div className="mt-6 flex min-h-64 items-end gap-1 overflow-x-auto pb-2">{summary.days.map(day=><div key={day.date} className="flex min-w-8 flex-1 flex-col items-center gap-2"><div className="flex h-52 items-end gap-0.5"><Bar value={day.menuViews} peak={peak} color="bg-violet-400" title={`${day.date}: ${day.menuViews} visitas`}/><Bar value={day.productViews} peak={peak} color="bg-cyan-400" title={`${day.date}: ${day.productViews} productos`}/><Bar value={day.videoPlays} peak={peak} color="bg-pink-400" title={`${day.date}: ${day.videoPlays} vídeos`}/><Bar value={day.cartAdds} peak={peak} color="bg-amber-400" title={`${day.date}: ${day.cartAdds} añadidos`}/></div><span className="text-[9px] text-slate-600">{day.date.slice(5)}</span></div>)}{!summary.days.length&&<Empty text="Aún no hay eventos en este periodo."/>}</div><div className="mt-3 flex flex-wrap gap-4 text-[10px] text-slate-400"><Legend color="bg-violet-400" label="Visitas"/><Legend color="bg-cyan-400" label="Productos"/><Legend color="bg-pink-400" label="Vídeos"/><Legend color="bg-amber-400" label="Carrito"/></div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><div className="flex items-center gap-2"><Store className="text-violet-300" size={20}/><h2 className="font-bold">Restaurantes con más actividad</h2></div><div className="mt-4 space-y-2">{summary.restaurants.slice(0,12).map((item,index)=><article key={item.id} className="grid grid-cols-[28px_minmax(0,1fr)_auto] items-center gap-3 rounded-xl border border-white/[.07] bg-black/20 p-3"><span className="text-center text-xs font-black text-slate-600">{index+1}</span><div className="min-w-0"><Link href={`/superadmin/restaurants/${item.id}`} className="block truncate text-sm font-semibold hover:text-violet-300">{item.name}</Link><p className="mt-1 text-[10px] text-slate-500">{item.videoPlays} vídeos · {item.cartAdds} carrito · {item.contactClicks} contactos</p></div><strong className="text-sm tabular-nums">{item.menuViews} visitas</strong></article>)}{!summary.restaurants.length&&<Empty text="Sin restaurantes con actividad."/>}</div></section>
      <section className="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><div className="flex items-center gap-2"><UtensilsCrossed className="text-pink-300" size={20}/><h2 className="font-bold">Productos más vistos</h2></div><div className="mt-4 space-y-2">{summary.products.slice(0,12).map((item,index)=><article key={item.id} className="grid grid-cols-[28px_minmax(0,1fr)_auto] items-center gap-3 rounded-xl border border-white/[.07] bg-black/20 p-3"><span className="text-center text-xs font-black text-slate-600">{index+1}</span><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.name}</p><p className="truncate text-[10px] text-slate-500">{item.restaurant} · {item.videoPlays} vídeos · {item.cartAdds} carrito</p></div><strong className="text-sm tabular-nums">{item.views}</strong></article>)}{!summary.products.length&&<Empty text="Sin productos vistos."/>}</div></section></div>
    <section className="mt-6 grid gap-4 rounded-3xl border border-white/10 bg-slate-950/50 p-5 sm:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2"><Languages className="text-cyan-300" size={20}/><h2 className="font-bold">Idiomas utilizados</h2></div><p className="mt-1 text-sm text-slate-500">Distribución de todos los eventos del periodo.</p></div><div className="grid grid-cols-3 gap-2"><Language label="Español" value={languageTotal?Math.round(summary.languages.es/languageTotal*100):0}/><Language label="Inglés" value={languageTotal?Math.round(summary.languages.en/languageTotal*100):0}/><Language label="Otros" value={languageTotal?Math.round(summary.languages.other/languageTotal*100):0}/></div></section>
    <p className="mt-4 text-xs leading-relaxed text-slate-600">Los eventos de reproducción de vídeo y carrito empiezan a contabilizarse desde esta versión; no se reconstruyen retroactivamente. Una reproducción se cuenta una sola vez por producto durante cada apertura de la carta.</p>
  </main>;
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase text-slate-500">{icon}{label}</div><p className="mt-3 text-3xl font-black tabular-nums">{value.toLocaleString("es-ES")}</p></div>}
function Rate({label,value,suffix="%"}:{label:string;value:number;suffix?:string}){return <div className="rounded-2xl border border-cyan-400/10 bg-cyan-400/[.04] p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-cyan-200">{value.toLocaleString("es-ES")}{suffix}</p></div>}
function Bar({value,peak,color,title}:{value:number;peak:number;color:string;title:string}){return <div title={title} className={`w-2 rounded-t-sm ${color}`} style={{height:`${Math.max(value?5:2,value/peak*190)}px`,opacity:value?1:.15}}/>}
function Legend({color,label}:{color:string;label:string}){return <span className="flex items-center gap-1.5"><i className={`h-2 w-2 rounded-full ${color}`}/>{label}</span>}
function Language({label,value}:{label:string;value:number}){return <div className="min-w-20 rounded-xl bg-white/[.04] p-3 text-center"><strong className="text-lg tabular-nums">{value}%</strong><p className="mt-1 text-[10px] text-slate-500">{label}</p></div>}
function Empty({text}:{text:string}){return <p className="col-span-full py-8 text-center text-sm text-slate-500">{text}</p>}
