import {BarChart3,Eye,MousePointerClick,Play,Share2,ShoppingBag,UtensilsCrossed} from "lucide-react";
import {activeRestaurant} from "@/lib/permissions";
import {analyticsDateSeries,summarizeAnalytics} from "@/lib/analytics";
import {BackButton} from "@/components/ui/back-button";

export default async function AnalyticsPage(){
  const {supabase,restaurant}=await activeRestaurant();
  const from=new Date();from.setUTCDate(from.getUTCDate()-29);
  const {data,error}=await supabase.from("menu_analytics_daily").select("event_date,event_type,event_count,dimension_key,product_id,locale,products(name)").eq("restaurant_id",restaurant.id).gte("event_date",from.toISOString().slice(0,10)).order("event_date");
  if(error)throw new Error(error.message);
  const rows=data??[];const summary=summarizeAnalytics(rows);const series=analyticsDateSeries(summary.days);const peak=Math.max(1,...series.map(item=>item.views));
  const spanish=rows.filter(row=>row.locale==="es").reduce((total,row)=>total+Number(row.event_count),0);const english=rows.filter(row=>row.locale==="en").reduce((total,row)=>total+Number(row.event_count),0);const languageTotal=spanish+english;
  return <main className="mx-auto max-w-6xl p-4 md:p-6"><div className="border-b border-slate-800 pb-4"><BackButton fallback="/dashboard"/><p className="mt-4 text-xs font-bold uppercase tracking-[.18em] text-violet-300">Últimos 30 días</p><h1 className="mt-1 text-2xl font-extrabold">Analíticas de la carta</h1><p className="mt-1 text-sm text-slate-400">Contadores agregados sin cookies, IP ni seguimiento de visitantes.</p></div>
    <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-6"><Metric icon={<Eye/>} label="Visitas" value={summary.totals.menuViews}/><Metric icon={<UtensilsCrossed/>} label="Productos vistos" value={summary.totals.productViews}/><Metric icon={<Play/>} label="Vídeos vistos" value={summary.totals.videoPlays}/><Metric icon={<ShoppingBag/>} label="Añadidos" value={summary.totals.cartAdds}/><Metric icon={<Share2/>} label="Compartidos" value={summary.totals.shares}/><Metric icon={<MousePointerClick/>} label="Contactos" value={summary.totals.contactClicks}/></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(280px,.6fr)]"><section className="rounded-3xl border border-white/10 bg-slate-950/40 p-5"><div className="flex items-center gap-2"><BarChart3 className="text-violet-300" size={20}/><h2 className="font-bold">Visitas diarias</h2></div><div className="mt-6 flex h-52 items-end gap-1.5">{series.map(item=><div key={item.date} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="opacity-0 text-[9px] tabular-nums text-slate-400 transition group-hover:opacity-100">{item.views}</span><div title={`${item.date}: ${item.views} visitas`} className="w-full min-w-1 rounded-t-md bg-gradient-to-t from-violet-600 to-cyan-400 transition hover:brightness-125" style={{height:`${Math.max(item.views?8:2,(item.views/peak)*160)}px`,opacity:item.views?1:.18}}/><span className="hidden text-[8px] text-slate-600 sm:block">{item.date.slice(8)}</span></div>)}</div></section>
      <aside className="space-y-5"><section className="rounded-3xl border border-white/10 bg-slate-950/40 p-5"><h2 className="font-bold">Productos más vistos</h2><div className="mt-4 space-y-3">{summary.products.slice(0,5).map((product,index)=><div key={product.id} className="flex items-center gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-violet-500/10 text-xs font-bold text-violet-300">{index+1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{product.name}</p><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-900"><div className="h-full rounded-full bg-violet-500" style={{width:`${Math.max(4,(product.views/Math.max(1,summary.products[0]?.views??1))*100)}%`}}/></div></div><strong className="text-sm tabular-nums">{product.views}</strong></div>)}{!summary.products.length&&<Empty/>}</div></section><section className="rounded-3xl border border-white/10 bg-slate-950/40 p-5"><h2 className="font-bold">Idioma utilizado</h2><div className="mt-4 grid grid-cols-2 gap-3"><Language label="Español" value={languageTotal?Math.round(spanish/languageTotal*100):0}/><Language label="Inglés" value={languageTotal?Math.round(english/languageTotal*100):0}/></div></section></aside>
    </div>{summary.totals.menuViews===0&&<div className="mt-6 rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">Las estadísticas aparecerán cuando la carta publicada reciba visitas.</div>}
  </main>;
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-slate-950/40 p-4"><div className="flex items-center gap-2 text-xs uppercase text-slate-500">{icon}{label}</div><p className="mt-3 text-3xl font-black tabular-nums">{value}</p></div>}
function Language({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-white/[.04] p-3 text-center"><strong className="text-xl tabular-nums">{value}%</strong><p className="mt-1 text-xs text-slate-500">{label}</p></div>}
function Empty(){return <p className="text-sm text-slate-500">Todavía no hay visualizaciones.</p>}
