import Link from "next/link";
import {BarChart3,ChevronRight,Download,Eye,Lightbulb,MousePointerClick,Play,ShoppingBag,Sparkles,UtensilsCrossed} from "lucide-react";
import {activeRestaurant} from "@/lib/permissions";
import {analyticsDateSeries,summarizeAnalytics} from "@/lib/analytics";
import {ANALYTICS_PERIODS,analyticsChange,analyticsPeriodRange,parseAnalyticsPeriod,weeklySalesSummary} from "@/lib/analytics-report";
import {BackButton} from "@/components/ui/back-button";

const percentage=(value:number,total:number)=>total?Math.round(value/total*100):0;

export default async function AnalyticsPage({searchParams}:{searchParams:Promise<{days?:string}>}){
  const days=parseAnalyticsPeriod((await searchParams).days);const range=analyticsPeriodRange(days);
  const {supabase,restaurant}=await activeRestaurant();
  const {data,error}=await supabase.from("menu_analytics_daily").select("event_date,event_type,event_count,dimension_key,product_id,locale,products(name,category_id,categories(name))").eq("restaurant_id",restaurant.id).gte("event_date",range.previousFrom).lte("event_date",range.currentTo).order("event_date");
  if(error)throw new Error(error.message);
  const rows=data??[];const summary=summarizeAnalytics(rows.filter(row=>row.event_date>=range.currentFrom));const previous=summarizeAnalytics(rows.filter(row=>row.event_date<=range.previousTo));
  const series=analyticsDateSeries(summary.days,days);const peak=Math.max(1,...series.map(item=>item.views));
  const addRate=percentage(summary.totals.cartAdds,summary.totals.productViews);const previousAddRate=percentage(previous.totals.cartAdds,previous.totals.productViews);const detailRate=percentage(summary.totals.detailOpens,summary.totals.productViews);const previousDetailRate=percentage(previous.totals.detailOpens,previous.totals.productViews);
  const opportunity=[...summary.products].filter(item=>item.views>=3).sort((a,b)=>(b.views-b.cartAdds)-(a.views-a.cartAdds))[0];const weeklyRange=analyticsPeriodRange(7);const weeklySummary=summarizeAnalytics(rows.filter(row=>row.event_date>=weeklyRange.currentFrom));const weekly=weeklySalesSummary(weeklySummary,restaurant.name);const shareUrl=`https://wa.me/?text=${encodeURIComponent(weekly.text)}`;
  return <main className="mx-auto max-w-7xl p-4 md:p-6"><div className="border-b border-stone-200 pb-4"><BackButton fallback="/dashboard"/><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-700">Últimos {days} días</p><h1 className="mt-1 text-2xl font-extrabold">Intención de compra</h1><p className="mt-1 text-sm text-slate-600">Comparado con los {days} días anteriores. Son señales agregadas, no ventas confirmadas.</p></div><div className="flex flex-wrap gap-2"><nav aria-label="Periodo de analíticas" className="flex border border-stone-300 bg-white p-1">{ANALYTICS_PERIODS.map(period=><Link key={period} href={`/dashboard/analytics?days=${period}`} className={`px-3 py-2 text-xs font-bold ${period===days?"bg-orange-600 text-white":"text-slate-600 hover:bg-stone-100"}`}>{period} días</Link>)}</nav><a href={`/api/dashboard/analytics/export?days=${days}`} className="inline-flex items-center gap-2 border border-stone-300 bg-white px-3 py-2 text-xs font-bold hover:bg-stone-100"><Download size={15}/>Descargar CSV</a></div></div></div>
    <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-6"><Metric icon={<Eye/>} label="Visitas" value={summary.totals.menuViews} previous={previous.totals.menuViews}/><Metric icon={<UtensilsCrossed/>} label="Platos vistos" value={summary.totals.productViews} previous={previous.totals.productViews}/><Metric icon={<Play/>} label="Vídeos iniciados" value={summary.totals.videoPlays} previous={previous.totals.videoPlays}/><Metric icon={<MousePointerClick/>} label="Detalles abiertos" value={summary.totals.detailOpens} previous={previous.totals.detailOpens}/><Metric icon={<ShoppingBag/>} label="Añadidos" value={summary.totals.cartAdds} previous={previous.totals.cartAdds}/><Metric icon={<Sparkles/>} label="Por recomendación" value={summary.totals.recommendationAdds} previous={previous.totals.recommendationAdds}/></section>

    <section className="mt-6 grid gap-4 md:grid-cols-3"><Rate label="Interés en detalles" value={detailRate} previous={previousDetailRate} note="Abren descripción o alérgenos"/><Rate label="Tasa de añadido" value={addRate} previous={previousAddRate} note="Añadidos por cada plato visto" emphasis/><Rate label="Peso de recomendaciones" value={percentage(summary.totals.recommendationAdds,summary.totals.cartAdds)} previous={percentage(previous.totals.recommendationAdds,previous.totals.cartAdds)} note="Añadidos desde venta sugerida"/></section>

    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(290px,.6fr)]"><section className="border border-stone-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><BarChart3 className="text-orange-700" size={20}/><h2 className="font-bold">Visitas diarias</h2></div><div className="mt-6 flex h-52 items-end gap-1">{series.map(item=><div key={item.date} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="sr-only">{item.date}: {item.views}</span><div title={`${item.date}: ${item.views} visitas`} className="w-full min-w-1 rounded-t-sm bg-orange-500 transition hover:bg-orange-600" style={{height:`${Math.max(item.views?8:2,(item.views/peak)*160)}px`,opacity:item.views?1:.15}}/></div>)}</div></section>
      <aside className="space-y-4"><section className="border-l-4 border-orange-500 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Lightbulb className="text-orange-700" size={19}/><h2 className="font-bold">Oportunidad detectada</h2></div>{opportunity?<><p className="mt-4 text-sm font-semibold">{opportunity.name}</p><p className="mt-1 text-xs leading-relaxed text-slate-600">Tiene {opportunity.views} visualizaciones y una tasa de añadido del {opportunity.addRate} %. Prueba otra portada, descripción, precio o recomendación.</p></>:<p className="mt-4 text-sm text-slate-600">Necesitamos al menos 3 visualizaciones por producto para sugerir una mejora.</p>}</section><section className="border border-stone-200 bg-white p-5"><h2 className="font-bold">Categorías con más intención</h2><div className="mt-4 space-y-3">{summary.categories.slice(0,5).map(category=><Rank key={category.id} name={category.name} value={category.cartAdds} suffix={`${category.addRate}%`}/>)}{!summary.categories.length&&<Empty/>}</div></section></aside>
    </div>

    <section className="mt-6 overflow-hidden border border-stone-200 bg-white"><div className="border-b border-stone-200 p-5"><h2 className="font-bold">Rendimiento por producto</h2><p className="mt-1 text-xs text-slate-600">Compara atención, información consultada y productos añadidos.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Producto</th><th className="px-4 py-3">Vistas</th><th className="px-4 py-3">Vídeo</th><th className="px-4 py-3">Detalles</th><th className="px-4 py-3">Añadidos</th><th className="px-4 py-3">Tasa</th></tr></thead><tbody className="divide-y divide-stone-100">{summary.products.map(item=><tr key={item.id}><td className="px-5 py-3"><strong>{item.name}</strong><p className="text-xs text-slate-500">{item.categoryName}</p></td><td className="px-4 py-3 tabular-nums">{item.views}</td><td className="px-4 py-3 tabular-nums">{item.videoPlays}</td><td className="px-4 py-3 tabular-nums">{item.detailOpens}</td><td className="px-4 py-3 tabular-nums">{item.cartAdds}{item.recommendationAdds>0&&<span className="ml-1 text-xs text-orange-700">(+{item.recommendationAdds} sugeridos)</span>}</td><td className="px-4 py-3"><span className={`inline-flex min-w-12 justify-center px-2 py-1 text-xs font-bold ${item.addRate>=addRate&&item.addRate>0?"bg-emerald-100 text-emerald-800":"bg-stone-100 text-stone-700"}`}>{item.addRate}%</span></td></tr>)}{!summary.products.length&&<tr><td colSpan={6} className="p-8 text-center text-slate-500">Todavía no hay actividad de productos.</td></tr>}</tbody></table></div></section>
    {summary.totals.menuViews===0&&<div className="mt-6 border border-dashed border-stone-300 p-6 text-center text-sm text-slate-500">Las estadísticas aparecerán cuando la carta publicada reciba visitas.</div>}
    <section className="mt-6 border-l-4 border-orange-500 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-orange-700">Últimos 7 días</p><h2 className="mt-1 text-lg font-bold">Resumen semanal</h2><p className="mt-1 text-xs text-slate-500">Señales de intención, no ventas confirmadas.</p></div><a href={shareUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center bg-emerald-700 px-4 py-2 text-sm font-bold text-white hover:bg-emerald-800">Compartir por WhatsApp</a></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><SummaryValue label="Visitas" value={String(weeklySummary.totals.menuViews)}/><SummaryValue label="Añadidos" value={String(weeklySummary.totals.cartAdds)}/><SummaryValue label="Destacado" value={weekly.topProduct?.name??"Sin datos"}/></div><div className="mt-4 border-t border-stone-200 pt-4"><p className="text-xs font-bold uppercase text-slate-500">Acciones recomendadas</p><ul className="mt-2 grid gap-2 text-sm text-slate-700">{weekly.actions.map(action=><li key={action}>• {action}</li>)}{!weekly.actions.length&&<li>• Sigue compartiendo la carta y revisa la evolución semanal.</li>}</ul></div></section>
  </main>;
}

function ChangeBadge({current,previous}:{current:number;previous:number}){const change=analyticsChange(current,previous);return <span className={`text-[10px] font-bold ${change.tone==="up"?"text-emerald-700":change.tone==="down"?"text-red-600":"text-slate-500"}`}>{change.label} <span className="font-normal text-slate-400">vs. anterior</span></span>}
function Metric({icon,label,value,previous}:{icon:React.ReactNode;label:string;value:number;previous:number}){return <div className="border border-stone-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-[10px] font-bold uppercase text-slate-500">{icon}{label}</div><p className="mt-3 text-3xl font-black tabular-nums">{value}</p><ChangeBadge current={value} previous={previous}/></div>}
function Rate({label,value,previous,note,emphasis=false}:{label:string;value:number;previous:number;note:string;emphasis?:boolean}){return <article className={`border p-4 ${emphasis?"border-orange-300 bg-orange-50":"border-stone-200 bg-white"}`}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xs text-slate-600">{note}</p><ChangeBadge current={value} previous={previous}/></div><strong className="text-3xl tabular-nums">{value}%</strong></div></article>}
function Rank({name,value,suffix}:{name:string;value:number;suffix:string}){return <div className="flex items-center gap-3"><ChevronRight size={15} className="text-orange-700"/><span className="min-w-0 flex-1 truncate text-sm">{name}</span><strong className="text-sm tabular-nums">{value}</strong><span className="w-10 text-right text-xs text-slate-500">{suffix}</span></div>}
function Empty(){return <p className="text-sm text-slate-500">Todavía no hay actividad.</p>}
function SummaryValue({label,value}:{label:string;value:string}){return <div className="bg-stone-50 p-3"><p className="text-[10px] font-bold uppercase text-slate-500">{label}</p><p className="mt-1 truncate font-bold">{value}</p></div>}
